#+TITLE: MMR Barrier Problem
#+AUTHOR: JT Laune
#+DATE: <2022-02-08 Tue>
#+LATEX_CLASS: article
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \newtheorem{defn}{Definition}
#+STARTUP: latexpreview

* Start
Consider $n$ point *orbiters* with finite masses
$m_1,m_2,m_3,\ldots\ll M$, where $M$ is the mass of the primary about
which they orbit. Most generally, its Hamiltonian is:
#+begin_src latex
  \begin{align}
    \mathcal H
    &\simeq \sum^{n}_{i=1}\left(\frac12 \frac{\vec p_i\cdot\vec p_i}{m_i}
      -\frac{GMm_i}{2|\vec x_i|}
      -\sum_{j\neq i}^{n} \frac{Gm_im_j}{2|\vec x_i - \vec x_j|}
      \right), \\
  \end{align}
#+end_src
where $\vec x_i$ and $\vec p_i$ are the Cartesian position and momentum vectors, respectively.

* Assumptions, definitions, and notation
- Two orbiters, $i=1,2$
  - Internal/external duality around q=1
- Coplanar, $i_i=0$
- Eccentricities are small, $e_i\ll 1$
  - First order expansion in $e_i$
- Orbiter masses are small, $m_i\ll M$
- Near a first order MMR (1MMR), $j = 1, 2, \ldots$
#+attr_latex: :options [Runge-Lenz vector]
#+begin_defn
the Cartesian vector with magnitude @@latex:$e$@@ in the
direction of orbital perihelion
#+end_defn


* Scaling
We choose the following units
#+begin_src latex
  \begin{align}
  \frac{[GM_\odot][{\rm au}]}{4\pi^2[{\rm yr}]^2} = 1
  \end{align}
#+end_src
@@latex:\noindent@@ so that time $\tau(t) \equiv 2\pi t$ is the
dimensionless arc length parameterization of a circular orbit and $t$ is measured in years.

The dimensionless Hamiltonian is then
#+begin_src latex
  \begin{align}
    \hat{\mathcal H}
    &\simeq \sum^{n}_{i=1}\left(\frac12 \hat p_i\cdot\hat p_i
      -\frac{G\mu_i}{2|\hat x_i|} \right)
      - \sum_{j\neq i}^{n} \left(\frac{G\mu_i\mu_j}{2|\hat x_i - \hat x_j|}
      \right),\\
    &\equiv H_0 + H_1
  \end{align}
#+end_src
@@latex:\noindent@@ where $\hat x_i$ and $\hat p_i$ are the
dimensionless Cartesian coordinates and momenta.  The first sum $H_0$ is
known as the Keplerian Hamiltonian and is $\mathcal O(\mu_i)$; the second is the
$\mathcal O(\mu_i\mu_j)$ contribution from mutual interactions, $H_{1}$.

* Dimensionless parameters
We define:
#+begin_src latex
  \begin{align}
   q&\equiv \frac{m_1}{m_2}\quad\text{mass ratio with each other}\\ 
   \mu_i&\equiv \frac{m_i}{M}\quad\text{dimless mass}\\ 
   \mu_{\rm tot}&\equiv \mu_1+\mu_2\quad\text{total mass},\\ 
   \mu_{\rm ext}&\equiv \frac{m_{\rm ext}}{M}\quad\text{total mass},\\ 
  \end{align}
#+end_src
@@latex:\noindent@@
where $M$ is the primary mass.

* @@latex:Poincair\'e@@'s conjugate pair
We utilize the following dimensionless coordinate-momentum conjugate
pairs (aka @@latex:Poincair\'e@@ coordinates):
#+begin_src latex
  \begin{align}
    \lambda_i \longleftrightarrow\Lambda_i &= \mu_i\sqrt{\alpha_i} \\
    -\varpi_i \longleftrightarrow\Gamma_i &= \mu_i\sqrt{\alpha_i}(1-\sqrt{1-e_i^2}) \approx \frac12\mu_i\sqrt{\alpha_i}e_i^2,
  \end{align}
#+end_src
@@latex:\noindent@@
where $\varpi_i$ is the longitude of perihelion and $\lambda_i$ the mean longitude
of orbiter $m_i$.

* MMR
Index MMR locations with $j$, such that first order MMRs (hereafter ``1MMRS'') occur whenever
$n_1/n_2\simeq(j+1)/j$.
Near these points, the relative angle between these 

Near this point, the following geometric angles in the literal expansion of the perturbing
function (see [[cite:&murray_solar_2000][Murray and Dermott]] for details) have commensurate ``fast`` frequenc
#+begin_src latex

#+end_src


We may use the @@latex:Poincair\'e@@ elements to write
the dimensionless Hamiltonian as:
#+begin_src latex
  \begin{align}
  \label{eq:H_1}
    \mathcal{H}
    = -\frac{q^3}{2(1+q)^3 \Lambda_1^2}
      - \frac{1}{2(1+q)^3\Lambda_2^2}
     - \frac{\tilde\mu}{(1+q)^2 \Lambda_2^2}\left[
      f_1\sqrt{\frac{2\Gamma_1}{\Lambda_1}}\cos\theta_1
      +f_2\sqrt{\frac{2\Gamma_2}{\Lambda_2}}\cos\theta_2
      \right],
  \end{align}
#+END_SRC
@@latex:\noindent@@ where we have defined
$\tilde\mu=\mu_1\mu_2/(\mu_1+\mu_2)$ to be the reduced mass ratio.
and the $\theta_i$ are conjugate to $\Gamma_i$.  For the limiting
cases of $q\to \infty$ ($m_2=0$) or $q\to 0$ ($m_1=0$), the ratio
$\mathcal{H}/\Lambda_i$ reduces to the standard test particle
Hamiltonian found in [[cite:&murray_solar_2000][Murray and Dermott]] if the limits are taken
carefully.

* Formal constructions
The *Kepler problem* is a special case of the *2-body problem*.
Its solutions are...

* Hamiltonian Mechanics
* Dissipation
In the following, we characterize dissipation by its effects on each
planets' angular momentum (AM) and energy.  A planet's energy,
$\mathcal E$, is determined by its semimajor axis (sma), $a$:
#+begin_src latex
  \begin{align}
     \mathcal E = -\frac{1}{2a},
  \end{align}
  \noindent
#+end_src
@@latex:\noindent@@
where we have chosen units such that $GM=1$.
Angular momentum is given by
#+begin_src latex
  \begin{align}
  h = \mathcal E \sqrt{1-e^2}.
  \end{align}
#+end_src

We may characterize dissipation by its action on the ...
$\tau_{mi}(t)$ and $\tau_{ei}(t)$ by the instantaneous derivatives
#+begin_src latex
  \begin{align}
     \frac{\dot e_i}{e_i} &= - \frac{1}{\tau_e(t)} - \xi(t, \mathbf X_i)\frac{1}{\tau_m(t)} \\
     \frac{\dot a_i}{a_i} &= -\frac{1}{\tau_m(t)} - \zeta(t, \mathbf X_i)\frac{1}{\tau_e(t)},
  \end{align}
  \noindent
#+end_src
@@latex:\noindent@@
where the dot notation corresponds to the time derivative of the
orbital elements. The functions $\xi(t)$ and $\zeta(t)$ are the
coupling between the eccentricity damping, $\tau_e(t)$, and the
semimajor axis (sma) damping, $\tau_m(t)$.

bibliography:references.bib
bibliographystyle:unsrt
