* preamble                                                           :ignore:
#+TITLE: Architecture of Planetary Systems in Mean Motion Resonance
#+OPTIONS: author:nil date:nil toc:nil
#+LATEX_CLASS: mnras
#+LaTeX_CLASS_OPTIONS: [usenatbib]
#+latex_header: \usepackage{caption}
#+latex_header: \usepackage{tabularx}
#+latex_header: \usepackage{subcaption}
#+latex_header: \usepackage{pdfpages}
#+latex_header: \usepackage{float}
#+latex_header: \usepackage{booktabs}
#+latex_header: \usepackage{enumitem}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{tensor}
#+latex_header: \usepackage{ wasysym }
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{xcolor}
#+latex_header: \usepackage{cancel}
#+latex_header: \newcommand{\note}[1]{{\color{red} \large #1 }}
#+latex_header: \renewcommand{\O}{\mathcal{O}}
#+latex_header: \renewcommand{\d}{\partial}
#+latex_header: \renewcommand{\v}[1]{\boldsymbol{ #1 }}
#+latex_header: \renewcommand{\t}[1]{\tilde{ #1 }}
#+latex_header: \newcommand{\tg}{\t{g}}
#+latex_header: \newcommand{\vh}[1]{\hat{\boldsymbol{ #1 }}}
#+latex_header: \newcommand{\pp}[2]{\frac{\partial #1}{\partial #2}}
#+latex_header: \newcommand{\dd}[2]{\frac{d #1}{d #2}}
#+latex_header: \DeclarePairedDelimiter{\abs}{|}{|}
#+latex_header: \DeclarePairedDelimiter{\norm}{||}{||}
#+latex_header: \DeclarePairedDelimiter{\p}{(}{)}
#+latex_header: \DeclarePairedDelimiter{\we}{\langle}{\rangle}
#+latex_header: \title[MMR Architecture]{Architecture of Planetary Systems in Mean Motion Resonance}
#+latex_header: \author[Laune et al.]{
#+latex_header: JT Laune,$^{1}$
#+latex_header: Laetitia Rodet,$^{1}$
#+latex_header: and Dong Lai$^{1}$
#+latex_header: \\
#+latex_header: $^{1}$Department of Astronomy and Space Sciences, Cornell University\\}

#+begin_src latex
\maketitle
#+end_src

* Introduction

Even before the first detection of an exoplanetary system, planets
were predicted to migrate from their initial position due to
interactions with their natal protoplanetary disk
cite:lin79_tidal_torques_accret_discs_binar,goldreich_excitation_1979,goldreich_disk-satellite_1980-1.
The associated angular momentum and energy exchange acts to reshape
the orbital architecture during the first million years of a system's
life, in particular the planets' semimajor axes and eccentricities.
This process is collectively known as planetary migration
cite:nelson_planetary_2018.

When two planets' periods are related by an integer fraction $j$:$j+k$
(e.g. 2:1, 3:2), mutual gravitational interactions can lock orbits
into mean motion resonances (MMRs).  MMRs are characterized by the
libration of two angles specific to the values of $j$ and $k$.  If
$k=1$, i.e. $j$:$j+1$ for some $j$, the gravitational interactions are
first order in eccentricity and inclination.  The resonance angles for
first order MMRs are given by
#+BEGIN_SRC latex
  \begin{align}
  \label{circangles1}
   \theta_1 &= (j+1)\lambda_2 - \lambda_1 - \varpi_1 \\
  \label{circangles2}
   \theta_2 &= (j+1)\lambda_2 - \lambda_1 - \varpi_2.
  \end{align}
#+END_SRC
@@latex:\noindent@@ The mean longitudes of the inner and outer planets
are denoted by $\lambda_1$ and $\lambda_2$, respectively, and
$\varpi_1$ and $\varpi_2$ denote their longitudes of perihelion.  If
the angles $\theta_1$ and $\theta_2$ librate around $\pi$ and $0$,
respectively, the system is said to be in resonance.  As a planet
migrates, its resonance locations sweep across the disk and capture
planets into resonant pairs and chains.  The MMR equilibrium is
governed by various conditions which are well studied in the
literature
cite:henrard_second_1983,deck_migration_2015,goldreich_overstable_2014,xu_migration_2018,henrard_second_1983.
The resonant pair's path across the disk, characterized by the
direction, distance traveled, and migration and eccentricity damping
timescales, determines the final orbital architecture for the system
cite:cresswell_evolution_2006,cresswell_three-dimensional_2008.

In the past 40 years, exoplanet surveys have given us a wealth of
systems to test our understanding of disk migration and resonant
dynamics.  Thousands of exoplanet systems have been discovered, and,
although many resonant systems have been found, the proportion of such
systems is low compared to theoretical expectations based on disk
migration cite:fabrycky_architecture_2014.  In addition to the paucity
of planets in MMRs, there also seems to be an overabundance of planets
just outside of mean motion resonances, with period ratios slightly
larger than 2 or 3/2
cite:fabrycky_architecture_2014,choksi_sub-neptune_2020.  A system's
orbital architecture can reveal details about its history.
Commensurate period ratios may indicate past resonant interactions
within the planetary system, but the present state of the resonance
can only be determined by analyzing the behavior of the angles in
equations eqref:circangles1 and eqref:circangles2.  Furthermore, since
these angles are related by $\theta_2-\theta_1=\varpi_1-\varpi_2$,
this implies that a resonant pair of planets will have
$\Delta\varpi\equiv \varpi_1-\varpi_2\approx \pi$.

NASA's \emph{Kepler} mission observed several planet pairs near a
first-order resonance with constraints on $\Delta\varpi$, such as
Kepler-88 cite:weiss_discovery_2020 and Kepler-24
cite:antoniadou_exploiting_2020. Both of these systems are apsidally
anti-aligned ($\Delta\varpi\approx180^\circ$).  Kepler-9b and
Kepler-9c are near to the 2:1 resonace and apsidally anti-aligned, but
their angles $\theta_1$ and $\theta_2$ likely circulate.  However, a
puzzling resonant architecture has been discovered recently in the
system K2-19.

NASA's \emph{K2} mission initially discovered the planets K2-19b and c
near a 3:2 period ratio ($P_b=7.9$ d, $P_c=11.9$ d), and later on
planet K2-19d at $P_d=2.5$ d
cite:howell14_k2_mission,armstrong15_one_closes_exopl_pairs_to,sinukoff16_eleven_multip_system_fromk_masses.
K2-19 is a solar-type star ($M_*=0.88M_\odot$), planet b has
$M_{b}=10.8 M_{\oplus}$, and c has $M_{c}<10M_{\oplus}$.  Both outer
planets had moderate eccentricities $e_b\approx e_c\approx 0.2$.
Further observations revealed K2-19b and c to be apsidally
\emph{aligned}, with $\Delta\varpi\equiv \varpi_c-\varpi_b \approx
2\pm 2^\circ$ cite:petigura_k2-19b_2020.  Hence, the K2-19 system
poses a problem for the conventional understanding of planet migration
and resonance capture.

Investigating how K2-19 could have formed with $\Delta\varpi=0$
through resonance capture will offer us an insight into its dynamical
history as well as a better understanding of the genesis of extrasolar
orbital configurations.  In this paper, we review the analytically
simple migration model commonly used in the literature.  In Section
[[Standard Picture of Resonance Capture]], we present the classical picture of resonant capture
and explore the parameter space for the coupling between the resonant
eccentricities and the protoplanetary disk. We fail to find any disk
conditions which robustly lead to apsidal alignment.  In Section
[[Apsidal Angle]], we design a toy model which relies on eccentricity
diriving to a finite, non-zero value and argue that it can reproduce
the apsidal alignment between K2-19b and c. We demonstrate that the
orbital architecture of K2-19 can be explained by an external force
which pumps the eccentricities beyond their equilibrium values.

* Standard Picture of Resonance Capture
*** IC table                                                       :ignore:
#+ATTR_LATEX: :placement "" :mode table :environment tabular :align | l | c | c |
#+NAME: tab:ICs
#+CAPTION: Initial conditions for the integrations in this paper. The quantity
#+CAPTION: $\epsilon$ is the tolerance used in the numerical integrator.
|------------------------------+----------------------------------+----------------------------------|
|                              | Section 2                        | Section 3                        |
|------------------------------+----------------------------------+----------------------------------|
| $P_2/P_1 (t=0)$              | 1.6                              | 1.5                              |
|------------------------------+----------------------------------+----------------------------------|
| $e_1$, $e_2 (t=0)$           | $0.001$                          | $0.001$                          |
|------------------------------+----------------------------------+----------------------------------|
| $\theta_1$, $\theta_2 (t=0)$ | $\mathcal{U}[0^\circ,360^\circ]$ | $\mathcal{U}[0^\circ,360^\circ]$ |
|------------------------------+----------------------------------+----------------------------------|
| $e_{1d}$, $e_{2d}$           | $0$                              | $0, 0.1, 0.2$                    |
|------------------------------+----------------------------------+----------------------------------|
| $h$                          | 0.03                             | 0.03                             |
|------------------------------+----------------------------------+----------------------------------|
| $T_{e,0}$ [yr]               | 1000                             | 1000                             |
|------------------------------+----------------------------------+----------------------------------|
| $T_{e,1}/T_{e,2}$            | $1/q$, free parameter            | $1/q$                            |
|------------------------------+----------------------------------+----------------------------------|
| $T_{e,i}/T_{m,i}$            | $3.46h^2$                        | $3.46h^2$                        |
|------------------------------+----------------------------------+----------------------------------|
| $T$                          | $150\times\max(T_{e,1},T_{e,2})$ | $60\times\max(T_{e,1},T_{e,2})$  |
|------------------------------+----------------------------------+----------------------------------|
| $\epsilon$                   | $10^{-9}$                        | $10^{-9}$                        |
|------------------------------+----------------------------------+----------------------------------|
*** Dissipative forces                                             :ignore:
Planets embedded within a protoplanetary disk interact gravitationally
with the gas and lose angular momentum, leading to inward migration
towards the central star.  Disk torques vary with planet mass as well
as across semimajor axis; large outer planets lose angular momentum
quickly and sweep up inner planets into MMRs
cite:tanaka_three-dimensional_2004,xu_migration_2018.  In some
cases, the planet can gain angular momentum and migrate away from the
primary.

In this paper, we will ignore the detailed physics of planet-disk
interactions and instead implement a proxy for dissipative forces
parametrized by the eccentricity damping and migration timescales,
denoted by $T_{e,i}$ and $T_{m,i}$ for $i=1,2$.  We will denote all
quantities relevant to the inner planet with the subscript $1$, and the
outer with $2$.  The equations of motion for disk effects are:
#+begin_src latex
  \begin{align}\label{eq:disforce}
    \frac{\dot{e}_i}{e_i} &= -\frac{1}{T_{e,i}} \\
    \frac{\dot{a}_i}{a_i} &= -\frac{1}{T_{m,i}} -\frac{2e_i^2}{T_{e,i}}.
  \end{align}
#+end_src
@@latex:\noindent@@ This approximate migration model has been proposed
by citet:goldreich_disk-satellite_1980-1 and is used in most studies
of MMR capture
[[cite:goldreich_overstable_2014,xu_migration_2018][e.g.][]] In our
notation, $T_{m,i}>0$ $(<0)$ denotes inward (outward) migration.

We'll consider two planets with masses $m_1$ and $m_2$ around a star
of mass $M_*$. We define $\mu_i=m_i/M_*$ to be their mass fractions
and set $M_*=1M_\odot$ throughout. For typical, thin disk profiles, we
have
cite:tanaka_three-dimensional_2004,cresswell_three-dimensional_2008,xu_migration_2018
#+BEGIN_SRC latex
  \begin{align}
    \frac{T_{e,1}}{T_{e,2}}&= \frac1q\\
    T_{e,i}&=3.46 h^2 T_{m,i},
  \end{align}
#+END_SRC
@@latex:\noindent@@ where $q=m_1/m_2$ is the mass ratio and $h$ is the
aspect ratio of the disk.  To scale the dissipation times in the
integrations, we choose a parameter $T_{e,0}$ and set
#+BEGIN_SRC latex
  \begin{align}
    T_{e,1}&=T_{e,0}/\sqrt{q}\\
    T_{e,2}&= T_{e,0}\sqrt{q}.
  \end{align}
#+END_SRC
@@latex:\noindent@@ We must have $1/T_{m,1} - 1/T_{m,2} < 0$ for
convergent (i.e. $\abs{a_1-a_2}$ is shrinking) inward migration, and
vice versa for outward migration.  Hence, for $q>1$, we set $T_{m,i}<
0$; for $q<1$, we set $T_{m,i}>0$.  For all of the runs in this paper,
we choose $h=0.03$ and $T_{e,0}=1000~\rm{years}$.

** Resonant Hamiltonian
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{./standard-example-h-0.03-Tw0-1000}.png}
    \caption{Standard MMR capture process for $h=0.1$ and $q=2$. The
      outer planet $m_2$ starts wide of resonance and is captured near
      $t=2000$ yrs, after which the two angles $\theta_1\to180^\circ$
      and $\theta_2\to 0^\circ$.  While in resonance, the $e_i$ values
      are driven to equilibrium and the periapses are antialigned.}
    \label{fig:standardex}
  \end{figure*}
#+END_SRC

*** Resonant Hamiltonian                                           :ignore:
When two planets have commensurate period ratios, $j$:$j+k$ where
$j,k$ are integers, their gravitational interactions may lock them
into a mean motion resonance (MMR).  As young planets migrate within
their disk, if the migration is convergent, they cross MMR period
ratios and may be captured. In our paper, we will be considering only
first order MMRs, which occur when $n_2/n_1 = j/j+1$, where $n_1,n_2$
are the planets' mean motions.

The Hamiltonian of a system with two planets near a first order MMR is
cite:murray_solar_2000:
#+BEGIN_SRC latex
  \begin{align}
    H_{\rm kep} = & -\frac{G M m_{1}}{2 a_{1}}-\frac{G M m_{2}}{2 a_{2}}\\
    H_{\rm res} = & -\frac{G m_{1} m_{2}}{a_{2}}
                    \left[
                    f_{1} e_{1} \cos \theta_{1} 
                    +f_{2} e_{2} \cos \theta_{2}\right]\\
    H_{\rm sec} = &-\frac{G m_{1} m_{2}}{a_{2}}\left[f_{3} (e_1^2 + e_2^2)
                    +f_4e_1e_2\cos(\varpi_2-\varpi_1)
                    \right] \\
  \label{hamiltonian}
    H = &~ H_{\rm kep} + H_{\rm res}+ H_{\rm sec}. 
  \end{align}
#+END_SRC
@@latex:\noindent@@ Here, the $f_i$ are functions of the semimajor
axis ratio $\alpha=a_1/a_2$ that can be found in Appendix B of
citet:murray_solar_2000 as
#+BEGIN_SRC latex
  \begin{align}
  \label{coefficients}
    f_1 &= \frac12[2(j+1)+\alpha D]b_{1/2}^{(j+1)}(\alpha); f_1(\alpha_{2:3})\approx 2.0 \\
    f_2 &= -\frac12[-1+2(j+1)+\alpha D]b_{1/2}^{(j)}(\alpha);f_2(\alpha_{2:3}) \approx -2.5\\
    f_3 &= \frac18[2\alpha D + \alpha^2 D^2]b_{1/2}^{(0)}(\alpha); f_3(\alpha_{2:3})\approx 1.15\\
    f_4 &= \frac14[2-2\alpha D - \alpha^2 D^2]b_{1/2}^{(1)}(\alpha); f_4(\alpha_{2:3})\approx -2.0, \\
  \end{align}
#+END_SRC
@@latex:\noindent@@ where $D$ denotes the derivative operator with
respect to $\alpha$ and the $b_{l}^m$ are Laplace coefficients.  In
our numerical integrations, we evaluate them at the instantaneous
semimajor axis ratio.  However, $f_1$ and $f_2$ depend weakly on
$\alpha$, and so in our analytical treatment we may ignore their
derivatives to good approximation.  $H_{\rm kep}$ is the standard
Keplerian Hamiltonian; $H_{\rm res}$ the resonant interactions between
the planets of order $\O(e_i)$; and $H_{\rm sec}$ the secular
interactions.  The two resonant angles are given as in equations
eqref:circangles1 and eqref:circangles2.

The Hamiltonian system defined by equation eqref:hamiltonian admits
seven independent coupled ordinary differential equations ($\dot a_i,
\dot e_i, \dot\theta_i, \dot\varpi_i$), which we may integrate
together with the effects of dissipation to simulate MMR capture.  We
utilize the $\mathtt{scipy}$ Python package with the Runge-Kutta
method of order 5(4) and a relative and absolute tolerance
$\epsilon=10^{-9}$.  The resonance angles are initialized over a
uniform distribution between $0^\circ$ and $360^\circ$.  At $t=0$, we
set $a_1=1~\mathrm{au}$, $P_2/P_1=1.6$, and $e_1=e_2=0.001$.  Table
ref:tab:ICs summarizes our simulation parameters for this section and
Section [[Apsidal Angle]].

An example of MMR capture is given in Figure ref:fig:standardex.  The
period ratio $P_2/P_1$ initially starts wide of the nominal resonance
value of $1.5$.  After around $2~\rm{kyr}$ of convergent migration,
the planets are caught into MMR, indicated by the stabilization of
$\theta_1$ to $180^\circ$ and $\theta_2$ to $0^\circ$.  The planets'
eccentricities level off at their equilibrium values near $e_1\approx
0.02$ and $e_2\approx0.04$, and the planets become apsidally
anti-aligned with $\varpi_1-\varpi_2\approx 180^\circ$.

In this paper, we will use the term "resonance" loosely to mean the
libration of an angle such as $\theta_1$, $\theta_2$, and later on
$\hat\theta$.  We'll also use the angle itself to refer to the
resonance, i.e. the planets $m_1$ and $m_2$ in Figure
ref:fig:standardex are caught into both $\theta_1$ and $\theta_2$,
respectively, since those angles are librating.

During the migration phase, planets typically retain small
eccentricities. Indeed, the standard circular MMRs (angles $\theta_1$
and $\theta_2$) have resonance widths which decrease with $e$,
and so small eccentricities are necessary for capture.  Most studies
neglect the secular terms in $H_{\rm sec}$ because they are second
order in eccentricity.  However, if eccentricities are excited,
secular terms play an important role, and so we include them in our
analysis.

** Equilibrium
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \begin{subfigure}[t]{0.225\textwidth}
    \includegraphics[width=1\textwidth]{{standard-eeqs-Tm2--454146-Tw0-1000}.png}
    \caption{ }
    \label{fig:standardeqecc}
    \end{subfigure}
    \begin{subfigure}[t]{0.225\textwidth}
    \includegraphics[width=1\textwidth]{{standard-pomega-Tm2--454146-Tw0-1000}.png}
    \caption{ }
    \label{fig:standardDpom}
    \end{subfigure}
    \caption{\emph{(a)} Analytical equilibrium values are plotted
      as dashed lines for various values of $q$. The points
      indicate time averaged numerical results from integrating the
      time-dependent equations of motion.  Error bars indicate the
      standard deviation of the eccentricities; most fall within
      the marker for eccentricity.  Simulations without secular
      effects showed only negligible differences, and so they were
      not included.  \emph{(b)} Same as \emph{(a)}, but for
      $\Delta\varpi$. Simulations without secular effects did show
      significant differences, and so they have been included.}
  \label{fig:standard}
  \end{figure}
#+END_SRC

*** Equilibrium                                                    :ignore:
The MMR capture in Figure ref:fig:standardex leads to an equilibrium
state in period ratio, resonant angles, eccentricities, and
$\Delta\varpi$.  The Hamiltonian in equation
[[eqref:hamiltonian]], including the dissipative terms, admits the
following three equations for equilibrium values of
$(e_1,e_2,\theta_1,\theta_2)$:
#+begin_src latex
  \begin{equation}
  \label{dote1}
    \dot e_1 = \frac{\mu_2}{\alpha_2} [f_1\sin(\theta_1) - De_2 \sin(\gamma_2-\gamma_1)] - \frac{e_1}{T_{e,1}}=0
  \end{equation}
  
  \begin{equation}
  \label{dote2}
    \dot e_2 = \frac{q\mu_2}{\alpha_2} [f_2\sin(\theta_2) - De_1 \sin(\gamma_1-\gamma_2)]- \frac{e_2}{T_{e,2}}=0
  \end{equation}
  
  \begin{align}
  \label{dotdpom}
    \frac{d}{dt}\Delta\varpi \equiv \dot\varpi_1-\dot\varpi_2
    &= \frac{\mu_2}{\alpha_2} \left[ \frac{f_1\cos\theta_1}{\alpha_1^{1/2} e_1}
       - \frac{qf_2\cos\theta_2}{\alpha_2^{1/2}e_2}\right.\nonumber \\
    &\quad+ \left.\frac{2C}{\alpha_1^{1/2}} + \frac{De_2}{\alpha_1^{1/2} e_1}
      - \frac{2qC}{\alpha_2^{1/2}} - \frac{qDe_1}{ \alpha_2^{1/2}e_2}\right]=0.
  \end{align}
#+end_src

Moreover, absent any dissipative or secular forces, the following quantities are
conserved:
#+begin_src latex
  \begin{align}
    J &= \Lambda_1\sqrt{1-e_1^2} + \Lambda_2\sqrt{1-e_2^2}\\
    G &= \frac{j+1}{j} \Lambda_1 + \Lambda_2,
  \end{align}
#+end_src
@@latex:\noindent@@ where $\Lambda_1 = q\sqrt{a_1/a_0}$ and
$\Lambda=\sqrt{a_2/a_0}$ assuming the Hamiltonian has been scaled by
the quantity $GM_*m_2/a_0$.  The quantity $J$ is the angular momentum
of the system, and $G$ is an integral of motion for the the
Hamiltonian $H_{\rm kep}+H_{\rm res}$ in equation eqref:hamiltonian.
Define $\eta$ to be the ratio of $J$ and $G$,
#+begin_src latex
  \begin{align}
    \eta(\alpha, e_1, e_2) &\equiv - 2(q/\alpha_0+1)\p*{\frac{J}{G}-\left.\frac{J}{G}\right|_{0}},
  \end{align}
#+end_src
@@latex:\noindent@@
where $\alpha_0 = (j/(j+1))^{3/2}$ and $\left(J/G\right|_{0}$ is
evaluated at $e_i=0$ and $\alpha=\alpha_0$.
Thus, we have $\eta(\alpha_0, 0, 0)=0$ and the corresponding Taylor expansion yields
#+begin_src latex
  \begin{align}
    \eta \approx -\frac{q(\alpha-\alpha_0)}{j\sqrt{\alpha_0}(q/\alpha_0+1)} + q\sqrt{\alpha_0}e_1^2 + e_2^2
  \end{align}
#+end_src
@@latex:\noindent@@
The equation of motion for $\eta$ is then given by
#+begin_src latex
  \begin{align}
  \label{doteta}
    \dot\eta = \frac{q\alpha_0^{1/2}}{j(q\alpha_0^{-1}+1)}&\left[ \frac{1}{T_{m2}} - \frac{1}{T_{m1}}
        + \frac{2e_1^2}{T_{e1}}- \frac{2e_2^2}{T_{e2}} \right] \nonumber\\
      &- q\alpha_0^{1/2}\frac{2e_1^2}{T_{e1}} - \frac{2e_2^2}{T_{e2}}=0.
  \end{align}
#+end_src
@@latex:\noindent@@
We note that the only contribution to $\dot{\eta}$ is from dissipative effects.

By solving the four equations [[eqref:dote1]] -- eqref:dotdpom and
[[eqref:doteta]] , we can calculate the equilibrium values for the system.
In the standard picture and neglecting secular terms (i.e., for small
$e_i$), equations [[eqref:dote1]] and [[eqref:dote2]] show
$\sin(\theta_i)\approx 0$.  Equation [[eqref:dotdpom]] gives us
$\abs{\cos\theta_i} \approx 1$ and $\cos\theta_1 = -\cos\theta_2$, but
the solution $(\theta_1,\theta_2)=(0,\pi)$ is unstable.  Hence,
$\theta_1\approx\pi$ and $\theta_2\approx 0$ in equilibrium.  Since
$\theta_1-\theta_2 = \varpi_2-\varpi_1$, we therefore see that
convergent migration produces anti-aligned periapses.  We confirm this
in the time-dependent integration in Figure ref:fig:standardex.

*** Standard model                                                 :ignore:
The equilibrium $e_i$'s and $\Delta\varpi$'s for comparable mass
planets $(q\in[0.5,2])$ are given in Figures ref:fig:standardeqecc and
[[ref:fig:standardDpom]].  Analytical solutions to the equilibrium
equations are plotted as dashed lines.
We compare the analytical results to a numerical integration of the 
time-dependent differential equations from Hamiltonian
eqref:hamiltonian and plot the average $e_1$, $e_2$, and
$\Delta\varpi$ over the last 10% of the timespan.  These results are
calculated with outward migration for $q>1$ and inward migration for
$q<1$.

As we can see in Figures ref:fig:standardeqecc and
ref:fig:standardDpom, the final averaged eccentricities for $m_1$ and
$m_2$ go approximately as $e_2/e_1 \sim q$. As expected, the
$\Delta\varpi$ average values are all very close to $\pi$. The
numerical and analytical results largely agree.  In the next two
sections, we will explore slightly modified models by varying the
ratio $T_{e,1}/T_{e,2}$ to test whether they can
produce apsidal alignment.

** Eccentricity damping timescales
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.3\textwidth]{{./varyTe-eeqs-h-0.03-Tw0-1000}.png}
    \caption{ Equilibrium eccentricity values for a range of
      $T_{e,1}/T_{e,2}\in[0.2,10]$ are plotted for three
      different values of $q=0.5,1.0,$ and $2.0$. The points and
      errorbars are calculated in the same way as
      \ref{fig:standard}.  The dashed lines indicate analytical
      estimates for $e_i$.}
    \label{fig:eqecc}
  \end{figure}
#+END_SRC

#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.3\textwidth]{{./varyTe-pomega-h-0.03-Tw0-1000}.png}
    \caption{Same as \ref{fig:eqecc} but for $\Delta\varpi$.}
    \label{fig:eqDpom}
  \end{figure}
#+END_SRC
*** Damping Timescales                                             :ignore:
Up until now, we have strictly been considering the standard picture
of planet migration -- with $T_{e,1}/T_{e,2} = 1/q$ and
$T_{e,i}=3.46h^2T_{e,i}$ -- which always gives rise to apsidal
anti-alignment for reasonable disk conditions ( $h\sim 0.1$,
$T_{e,i}\sim h^2 T_{m,i}$ ). This simple parametrized model will always
fail to capture all of the complicated hydrodynamics of real
astrophysical disks. We can therefore easily expect a difference in
the ratio $T_{e,1}/T_{e,2}$ over an order of magnitude.
We would like to determine the effects of the eccentricity damping
ratio on the equilibrium values of $e_i$ and whether such
a change could lead to apsidal alignment.

We explore this possibility in Figures ref:fig:eqecc and
ref:fig:eqDpom. The ratio $T_{e,1}/T_{e,2}$ varies freely between
$0.2$ and $10$, regardless of the mass ratio.  Initially, we attempted
to extend this range to $T_{e,1}/T_{e,2}=0.1$, but the system
eventually escapes resonance for all $q=0.5$, $1$, and $2$ and no
equilibrium is reached.  The migration timescales are set to
$\abs{T_{m,i}}=T_{e,i}/3.46 h^2$.  For $T_{e,1}<T_{e,2}$, then, we set
$T_{m,i}>0$, corresponding to outward migration, and vice versa for
$T_{e,1}>T_{e,2}$.

For comparable mass planets with $q=0.5$, $1$, and $2$, varying the
ratio $T_{e,1}/T_{e,2}$ around $1/q$ modifies the final equilibrium
eccentricities by a roughly similar factor, as seen in Figure
ref:fig:eqecc. The eccentricity ratio $e_1/e_2$ is largely unchanged,
yet the magnitudes $e_1$ and $e_2$ are larger for more extreme values
of $T_{e,1}/T_{e,2}$.  The dashed lines plot the analytic results from
solving equations [[eqref:dote1]] -- [[eqref:doteta]]; these findings
reproduce the numerical results.

The corresponding values for $\Delta\varpi$ are shown in Figure
ref:fig:eqDpom. In all cases, the analytic equilibrium
equations predict $\Delta\varpi\approx 180^\circ$, and the numerical
integrations agree.  We note that the equilibrium solutions given in
Figures ref:fig:standard - ref:fig:eqDpom are not continuous across
the line $T_{e,1}/T_{e_2} = 1$ (i.e. $q=1$ in Figure ref:fig:standard), which
is where we reverse the migration direction to ensure it is
convergent. Variations in the eccentricity damping ratio cannot
account for apsidal alignment.  

* Apsidal Angle
As we have seen, capture into the $\theta_1$ and $\theta_2$ resonance
always leads to $\Delta\varpi\approx 180^\circ$ due to their equilibrium
values being close to $180^\circ$ and $0^\circ$, respectively.  The apsidally
anti-aligned K2-19 system therefore poses a problem for our standard
model.  In order to match this observation, either $\theta_1$,
$\theta_2$, or both angles must circulate.

** Eccentricity driving forces
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{inres-driving-example-h-0.03-Tw0-1000-q2.0}.png}
    \caption{Here we have set $e_{1,d}=0.2$ with $h=0.03$ and $q=2$.
      After about 10~kyr, the system escapes the circular resonances
      (i.e., both $\theta_1$ and $\theta_2$ circulate) and becomes
      apsidally aligned.}
    \label{fig:drivingex}
  \end{figure*}
#+END_SRC
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{inres-driving-perpendicular-example-h-0.03-Tw0-1000-q2.0}.png}
    \caption{Here we have set $e_{2,d}=0.2$ with $h=0.03$ and $q=2$.
      After about 10~kyr, the system escapes the circular resonances
      and $\Delta\varpi$ approaches $90^\circ$. We see $\theta_2$
      still librates around $0^\circ$, but $\theta_1$ has shifted to
      a libration center near $90^\circ$ rather than $180^\circ$.}
    \label{fig:perpex}
  \end{figure*}
#+END_SRC
*** forces                                                         :ignore:
The planets K2-19b and c are moderately eccentric, with
$e_{b}\approx e_c\approx 0.2$ citep:petigura_k2-19b_2020.
One way of escaping the circular $\theta_i$ resonances is to
artificially drive the eccentricity of the system to larger values,
where equation eqref:dotdpom may be broken.  We modify the
eccentricity damping for $m_i$ in equation eqref:eq:disforce to be
#+begin_src latex
  \begin{equation}
    \frac{\dot e_i}{e_i} = -\frac{(e_i-e_{i,d})}{T_{e,i}},
  \end{equation}
#+end_src
@@latex:\noindent@@ so that planet $m_i$ is  driven to
$e_{i,d}$ with a timescale of $T_{e,i}$.

In Figure ref:fig:drivingex, we demonstrate the feasibility of this
approach, where we integrate the time-dependent equations with an
eccentricity driven to $e_{1,d}=0.2$ for $q=2$.  We initalize the
system close to resonance with $e_{1}=e_2=0.001$ and $P_{2}/P_1 =
1.5$, where it is caught ($\theta_1$ and $\theta_2$ librate) for
around 8,000 years. Between $t=8,000$ and $10,000$ years, $e_1$ and
$e_2$ grow and the system subsequently breaks out of both the
$\theta_1$ and $\theta_2$ resonances.  At this point, both planets'
ecentricities are excited to about $e_i\approx 0.2$ and the planets
become apsidally aligned as $\Delta\varpi$ librates around $0^\circ$
with a large amplitude.  Despite the circulation of both resonance
angles, the period ratio remains locked very close to the nominal
resonance location ($P_2/P_1= 1.5$). The system is caught in a
different type of resonance which we will study in the following
subsection.

On the other hand, for $e_{2,d}=0.2$ and $e_{1,d}$, the sytem displays
different resonance behavior.  We have plotted the details of this
system in Figure ref:fig:perpex.  The planets are immediately caught
in the $\hat\theta$ resonance, which persists throughout the
integration.  The angle $\theta_2$ librates with large amplitude
around its resonant value of $0^\circ$, while $\theta_1$ librates
around $270^\circ$ rather than $180^\circ$.  As a result,
$\Delta\varpi$ approaches $90^\circ$ and so the planets' perihelia are
now perpendicular to eachother.

** Reducing the Hamiltonian
*** figures (for the next section)                                 :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.45\textwidth]{{./S2-conserved-inres-q2.0}.png}
    \caption{In the left column, we have plotted
      $\mathcal{S}_1$ and $\mathcal{S}_2$ from equations
      (\ref{eq:sS1}) and (\ref{eq:sS2}) for three different
      combinations of of $e_{1d}$ and $e_{2d}$. Each row
      corresponds to one of the three different modes of
      resonance identified in this paper. The first row
      has $\Delta\varpi=0^\circ$, the second has
      $\Delta\varpi=180^\circ$, and the third has
      $\Delta\varpi=90^\circ$. In the right column, we
      plot the evolution of the resonant conserved
      quantity $S_2$ (equation (\ref{eq:S2eq})).  For
      $\Delta\varpi=0^\circ$, all three of
      $\mathcal{S}_1$, $\mathcal{S}_1$, and $S_2$ are
      conserved near zero. For the other two cases, $S_2$
      transitions to larger values near $\sim 0.1$ as the
      eccentricity driving reach an equilibrium.  Both
      $\mathcal{S}_1$ and $\mathcal{S}_2$ are excited to
      factors of a few in the apsidally aligned case (row
      2), while only $\mathcal{S}_1$ is excited for
      $\Delta\varpi=90^\circ$ (row 3).}
    \label{fig:S2cons}
  \end{figure}
#+END_SRC
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.45\textwidth]{{./relative-geometry}.png}
    \caption{Here we have plotted the eccentricity vectors
      $\mathbf{e}_1$, $\mathbf{e}_2$, and $\mathbf{\hat e}$
      in the reference frame of $\mathbf{e}_1$. Similar to
      Figure \ref{fig:S2cons}, each row is a different
      combination of $e_{1d}$ and $e_{2d}$ corresponding to
      the three different modes of resonance. The left
      column shows the initial conditions of the resonance,
      while the right column shows the evolution at late
      times. The top row ($\Delta\varpi=180^\circ$) exhibits
      little qualitative change besides the libration
      amplitudes shrinking to zero.  The second row
      ($\Delta\varpi=0^\circ$) shows $\mathbf{e}_2$
      circulating around $\mathbf{e}_1$ strictly contained
      to the second and third quadrants. The last row
      ($\Delta\varpi=90^\circ$) shows $\mathbf{e}_1$ and
      $\mathbf{e}_2$ transitioning into a perpendicular
      arrangement. Meanwhile, the $\mathbf{\hat e}$ vector
      circulates outside of both $\mathbf{e}_1$ and
      $\mathbf{e}_2$ in the second row, while remaining
      aligned with $\mathbf{e}_2$ in the last row.}
    \label{fig:relgeom}
  \end{figure}
#+END_SRC
*** Hhat                                                           :ignore:
A detailed analysis of the MMR Hamiltonian eqref:hamiltonian
illustrates the underlying dynamics behind the capture processes in
Figure ref:fig:drivingex which lead to apsidal alignment.  We show
that $\theta_1$ and $\theta_2$ are actually subresonances of a
resonance $\hat\theta$ which arises after transforming the system's
Hamiltonian so that it has only a single degree of freedom.  This
treatment naturally explains why $P_2/P_1$ is locked near $1.5$.


If we assume that the semimajor axis ratio $\alpha$ is stationary or
varying adiabatically, we may transform the resonant Hamiltonian
$H_{\rm Kep} + H_{\rm res}$ in equation [[eqref:hamiltonian]] into the
form
#+begin_src latex
  \begin{equation}
    \label{hhat}
    \hat H(\hat R,\hat\theta) = -3(\delta+1) \hat R + \hat R^2 - 2\sqrt{2\hat R} \cos(\hat\theta)
  \end{equation}
#+end_src
@@latex:\noindent@@ through a series of rotations in phase space.  For
the details of these transformations, see Appendix [[Reducing the
Hamiltonian to a single degree of freedom]].  The parameter $\delta$
quantifies the system's depth into resonance.  We do not include
$H_{\rm sec}$ in this analysis because it is second order in
eccentricities and does not qualitatively change the outcome of our
numerical integrations.

First order MMRs are typically treated as the circular restricted
three body problem (CR3BP), where one of the planets is a test
particle and the other is on a circular orbit. These are limiting
cases of the Hamiltonian given in equation eqref:hamiltonian for
comparable mass planets. For an inner (outer) test particle, $m_1=0$
($m_2=0$), $m_2$ ($m_1$) is finite, and $q$ approaches infinity
(zero).  In the CR3BP limit, the action angles are $\theta_1$ and
$\theta_2$ in equations eqref:circangles1, eqref:circangles2, and
eqref:hamiltonian for the internal and external cases, respectively.
The actions for the CR3BP are proportional to
#+begin_src latex
  \begin{align}
  \label{eq:R2limit}
    R_1  \propto \frac{e_1^2}{\mu_2^{2/3}}
  \end{align}
#+end_src
@@latex:\noindent@@ 
and
#+begin_src latex
  \begin{align}
  \label{eq:R1limit}
    R_2  \propto  \frac{e_2^2}{\mu_1^{2/3}} .
  \end{align}
#+end_src

One can see that the actions given above for the CR3BP are functions
of the test particles' eccentricities only, as the massive planets'
eccentricities are assumed to be zero.  On the other hand, for the
case where $q>0$ is finite, both planets will be on eccentric
osculating orbits.
Hence, we expect the action $\hat R$ in equation eqref:hhat
to be a function of both $e_1$ and $e_2$.

Define $\v{\hat e} = \abs{f_1}\v e_1 - \abs{f_2}\v e_2$ and $\hat e =
\abs{\v{\hat e}}$, where $\v e_i$ is the Runge-Lenz vector, i.e. the
vector with magnitude $e_i$ in the direction of perihelion.  The
action $\hat R$ then takes the form $\hat R \propto \tilde \mu
\hat e^2$, where $\tilde\mu = m_1m_2/(m_1+m_2)$ is the reduced mass of the
planets. In order to recover the actions given above for the
appropriate CR3BP limits, we have
#+begin_src latex
  \begin{align}
  \label{eq:R1hatlimit}
    \hat R \propto \frac{\hat e^2}{q^{2/3}\hat\mu^{2/3}}
  \end{align}
#+end_src
@@latex:\noindent@@ 
for $q < 1$
and
#+begin_src latex
  \begin{align}
  \label{eq:R2hatlimit}
    \hat R \propto \frac{q^{2/3}\hat e^2}{\hat\mu^{2/3}}
  \end{align}
#+end_src
@@latex:\noindent@@
for $q>1$.
The action angle is $\hat\theta$ which is given by
#+BEGIN_SRC latex
  \begin{align}
  \label{hattheta}
    \tan\hat{\theta}_1 = \frac{W_1}{w_1} = \frac{f_1 e_1\sin(\theta_1)
    + f_2e_2\sin(\theta_2)}{f_1e_1\cos(\theta_1) + f_2e_2\cos(\theta_2)}.
  \end{align}
#+END_SRC
@@latex:\noindent@@
Appendix [[Reducing the Hamiltonian to a single degree of freedom]]
describes the detailed behavior of $\hat H$, $\hat \theta$,
and $\hat R$ in the CR3BP limits,

** Three modes of resonance
*** modes of resonance                                             :ignore:
Under the assumption that the semimajor axes are stationary (or slowly
varying), the Hamiltonian in equation eqref:hamiltonian has two
degrees of freedom (dof): the angles $\theta_1$ and $\theta_2$.  By
transforming this Hamiltonian into the single dof form of equation
eqref:hhat the resonance admits the following conserved quantity:
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:s2}
    S_2 = q\sqrt{\alpha}f_2^2e_1^2
  +2\abs{f_1f_2}e_1e_2\cos(\varpi_1-\varpi_2) + \frac{f_1^2}{q\sqrt\alpha}e_2^2.
  \end{align}
#+END_SRC

By enforcing $dS_2/dt = 0$ together with the assumption $d\alpha/dt
\approx 0$, we arrive at the following equilibrium condition:
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:S2eq}
    \frac{dS_2}{dt} \propto e_1^2\left(\frac{e_1-e_{1\rm d}}{T_{e,1}}\right)\abs*{\frac{f_2}{f_1}}
    \mathcal{S}_1
    + e_2^2\left(\frac{e_2-e_{2\rm d}}{T_{e,2}}\right)
    \mathcal{S}_2
    = 0.
  \end{align}
#+END_SRC
@@latex:\noindent@@
where
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:sS1}
    \mathcal{S}_1=&\left[
                    q^2\alpha\abs*{\frac{f_2}{f_1}}
                    + \frac{e_2}{e_1}q\sqrt{\alpha}\cos(\varpi_1-\varpi_2)
                    \right]\\
    \label{eq:sS2}
    \mathcal{S}_2=&\left[
                    \abs*{\frac{f_2}{f_1}} q\sqrt{\alpha}
                    \frac{e_1}{e_2}\cos(\varpi_1-\varpi_2) + 1
                    \right].
  \end{align}
#+END_SRC

In Figure ref:fig:S2cons, we have plotted $\mathcal{S}_1$ and
$\mathcal{S}_2$ as well as $\dot S_2/S_2$ for three different
combinations of $e_{1d}$ and $e_{2d}$.  The top row is for the
standard eccentricity damping case where $e_{1d}=e_{2d}=0$.  Once the
system equilibrates, $S_2\approx 10^{-4}$ is well conserved (top left) and
small. Both $\mathcal{S}_1$ and $\mathcal{S}_2$ are also close to
zero. From equations eqref:eq:sS1 and eqref:eq:sS1, we see this
corresponds to $e_2/e_1 \sim q$, as we found in Section [[Standard
Picture of Resonance Capture]].

The second row corresponds to the integration shown in
ref:fig:drivingex, where $e_{1d}=0.1$ and $e_{2d}=0$.  Near the
beginning, while the system is still caught in the $\theta_1$ and
$\theta_2$ resonances, $\mathcal{S}_1$, $\mathcal{S}_2$, and $S_2$ are
small.  Once the $\theta_i$ resonances are broken, and only
$\hat\theta$ librates, they are excited to larger values.  The
quantities $\mathcal{S}_1$ and $\mathcal{S}_2$ undergo large periodic
oscillations away from zero, while $S_2$ grows and then stabilizes at
its new equilibrium value. The system's eccentricities oscillate in
such a way to conserve equation eqref:eq:S2eq.  The last row
corresponds to the integration in ref:fig:perpex, where $e_{2d}=0.2$
and $e_{1d}=0$ .  For this system, $\mathcal{S}_2$ is conserved close
to 0, while $\mathcal{S}_1$ grows to a magnitude similar to its value
in the apsidally aligned case.

The systems in Figures ref:fig:standardex, ref:fig:drivingex, and
ref:fig:perpex are representative of three different modes of
resonance, ones where $\Delta\varpi=180^\circ$,
$\Delta\varpi=0^\circ$, and $\Delta\varpi=90^\circ$,
respectively. These correspond to three different behaviors of the
quantities $\mathcal{S}_1$ and $\mathcal{S}_2$ while in resonance
under the influence of eccentricity forcing.

In Figure ref:fig:relgeom, we plot the eccentricity
vectors $\mathbf{e}_{1}$, $\mathbf{e}_{2}$, and $\mathbf{\hat e}$
in the reference frame which rotates with $\mathbf{e}_1$.
The three systems begin with the same configuration
caught in the $\theta_1$ and $\theta_2$ resonances,
where $\mathbf{e}_1$ and $\mathbf{e}_2$ are anti-aligned.
At later stages, the system without eccentricity driving
remains in this configuration with $\mathbf{\hat e}$
aligned with $\mathbf{e}_1$.

At later times, the second and third rows exhibit the
resonance behavior described above.  For the apsidally aligned case,
$\mathbf{e_2}$ circulates in a pattern strictly constrained to the
second and third quadrants, and $\mathbf{\hat e}$ circulates around the
other two vectors.  In the last row, $\mathbf{e}_1$ and $\mathbf{e}_2$
are perpendicular to each other and $\mathbf{\hat e}$ is aligned with
$\mathbf{e}_2$.

** Saturation eccentricities
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.4\textwidth]{{./Rhat-grid-q2.0-inres}.png}
    \caption{\emph{Left:} The resonance architecture for
      integrations spanning a grid of driving
      eccentricities. Systems which become unstable and
      escape resonance are excluded. Roughly, for
      $e_{1d}\gtrsim e_{2d}$, the system becomes aligned.
      For $e_{2d}>e_{1d}$, the system becomes perpendicular
      for large values of $e_{2d}$. The other simulations
      remain trapped in both of the $\theta_1$ and
      $\theta_2$ resonances.  \emph{Right:} The numerically
      averaged final eccentricities of the systems shown in
      the left panel. The apsidally aligned systems fall
      just below the line $e_2=e_1$. Their error bars
      correspond to the standard deviation of the
      eccentricities. The perpendicular systems fall just
      above the line $e_2=2e_1=qe_1$, while the anti-aligned
      systems fall just below it. Both have small librations
      compared to the aligned case.}
    \label{fig:Rhat-grid}
  \end{figure}
#+END_SRC
*** saturation eccs                                                :ignore:
Now that we have identified these three resonant modes, we briefly
explore the $(e_{1d},e_{2d})$ parameter space for the saturation
eccentricities for moderate values between $0$ and $0.3$.
In the left panel of Figure ref:fig:Rhat-grid,
we summarize the resonant behavior for each system on a grid
within the parameter space. Here, we have excluded
runs which become unstable and escape the resonance on the timescale
of our integrations. Roughly, for $e_{1d}\gtrsim e_{2d}$,
the system becomes apsidally aligned, while for $e_{2d} > e_{1d}$,
$\Delta\varpi=90^\circ$.

We have plotted the averaged final eccentricities in the right
panel of Figure ref:fig:Rhat-grid. The points share
the same color-coding as in the right panel.
The eccentricities for the aligned case fall roughly along
the line $e_1=e_2$. The perpendicular runs fall
slightly above the line $e_2=2e_1$ (i.e. $e_2/e_1=q$),
while the anti-aligned runs fall just under it.

* Conclusion




* Appendix :ignore:
@@latex:\clearpage@@
@@latex:\onecolumn@@
@@latex:\appendix@@
** Reducing the Hamiltonian to a single degree of freedom
*** Scaling the Hamiltonian
The Hamiltonian for two comparable mass planets near a first order $j:j+1$
resonance is
#+begin_src latex
\begin{align}
  H = -\frac{G M m_{1}}{2 a_{1}}-\frac{G M m_{2}}{2 a_{2}}
                 -\frac{G m_{1} m_{2}}{a_{2}}
                  \left[
                  f_{1} e_{1} \cos \theta_{1} 
                  +f_{2} e_{2} \cos \theta_{2}\right].
\end{align}
#+end_src
@@latex:\noindent@@ Define $m_{\rm tot} = m_1+m_2$ and $a_0$ to be the
scale length of the problem.  We will then scale the Hamiltonian by
$H_0 = GMm_{\rm tot}/a_0$, the time by the frequency $\omega_0 =
\sqrt{GM/a_0^3}$, and the canonical momenta by $\Lambda_0 = m_{\rm
tot} \sqrt{GMa_0}$.  The dimensionless Hamiltonian $\mathcal{H}$ is
then
#+BEGIN_SRC latex
  \begin{align}
    \mathcal{H} \equiv \frac{H}{H_0}
    = -\frac{m_1/m_{\rm tot}}{2a_1/a_0}
      -\frac{m_2/m_{\rm tot}}{2a_2/a_0}
    -\frac{\tilde m}{M (a_2/a_0)}\left[
      f_1e_1\cos\theta_1+f_2e_2\cos\theta_2
      \right],
  \end{align}
#+END_SRC
@@latex:\noindent@@
where $\tilde m = m_1m_2/m_{\rm tot}$ is the reduced mass.
The canonical momenta then become
#+BEGIN_SRC latex
  \begin{align}
    \Lambda_1 &= \frac{m_1}{m_{\rm tot}}\sqrt{\frac{a_1}{a_0}} \\
    \Lambda_2 &= \frac{m_2}{m_{\rm tot}}\sqrt{\frac{a_2}{a_0}} \\
    \Gamma_1 &= \frac{m_1}{m_{\rm tot}}\sqrt{\frac{a_1}{a_0}}
               \left(1-\sqrt{1-e_2^2}\right) \\
    \Gamma_2 &= \frac{m_2}{m_{\rm tot}}\sqrt{\frac{a_2}{a_0}}
               \left(1-\sqrt{1-e_2^2}\right)
  \end{align}
#+END_SRC
@@latex:\noindent@@
Restoring $\mathcal{H}$ with these momenta, we have
#+BEGIN_SRC latex
  \begin{align}
  \label{eq:H_1}
    \mathcal{H}
    = -\frac{q^3}{2(1+q)^3 \Lambda_1^2}
      - \frac{1}{2(1+q)^3\Lambda_2^2}
     - \frac{\tilde\mu}{(1+q)^2 \Lambda_2^2}\left[
      f_1\sqrt{\frac{2\Gamma_1}{\Lambda_1}}\cos\theta_1
      +f_2\sqrt{\frac{2\Gamma_2}{\Lambda_2}}\cos\theta_2
      \right],
  \end{align}
#+END_SRC
@@latex:\noindent@@ where we have defined $\tilde\mu=\tilde m/M$ to be
the reduced mass ratio.  We note that, as equation eqref:eq:H_1 is
written, the $\theta_i$ are not conjugate to $\Lambda_i$ or
$\Gamma_i$.  For the limiting cases of $q\to \infty$ ($m_2=0$) or
$q\to 0$ ($m_1=0$), $\mathcal{H}$ reduces to the standard test
particle Hamiltonian found in citet:murray_solar_2000.
*** Reducing rotation
Now, we would like to find the momenta conjugate to the fast
coordinates $\lambda_i$ while keeping the slowly varying $\theta_i$.
A canonical transformation preserves the form
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:dH} 
    d\mathcal{H}
    &= \Lambda_1 d\lambda_1+\Lambda_2d\lambda_2
      + \Gamma_1d\gamma_1+\Gamma_2d\gamma_2\nonumber\\
    &= \Gamma_1 d\theta_1 + \Gamma_2 d\theta_2
      +J_1 d\lambda_1+J_2d\lambda_2 .
  \end{align}
#+END_SRC
@@latex:\noindent@@
We can solve the set of equations in eqref:eq:dH for
#+BEGIN_SRC latex
  \begin{align}
  \label{eq:J1}
  J_1 &= \Lambda_1 + j(\Gamma_1+\Gamma_2)\\
  \label{eq:J2}
  J_2 &= \Lambda_2 - (j+1)(\Gamma_1+\Gamma_2),
  \end{align}
#+END_SRC
@@latex:\noindent@@ where $\Gamma_i$ and $J_i$ are conjugate to
$\theta_i$ and $\lambda_i$, respectively.
The coordinates $\lambda_1$ and $\lambda_2$
no longer appear in the Hamiltonian,
which means $J_1$ and $J_2$ are constants of motion and
equation eqref:eq:H_1 may be written
in the following form:
#+BEGIN_SRC latex
  \begin{align}
  \label{eq:H_2}
    \mathcal{H}
    = \mathcal{H}_0(\Gamma_1+\Gamma_2; J_1, J_2, q)
                    + \mathcal{H}_{\rm pert}(\Gamma_1,\Gamma_2; J_1, J_2, q),
  \end{align}
#+END_SRC
@@latex:\noindent@@
where
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:H01}
    \mathcal{H}_0(\Gamma_1+\Gamma_2; J_1, J_2, q)
    = -\frac{q^3}{2(1+q)^3(J_1-j(\Gamma_1+\Gamma_2))^2}
    -\frac{1}{2(1+q)^3(J_2+(j+1)(\Gamma_1+\Gamma_2))^2} 
  \end{align}
#+END_SRC
@@latex:\noindent@@
and
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:Hpert1}
    \mathcal{H}_{\rm pert}(\Gamma_1,\Gamma_2; J_1, J_2, q)
    = -\frac{\tilde\mu}{(1+q)^2(J_2+(j+1)(\Gamma_1+\Gamma_2))^2}
    \left[
      f_1\sqrt{\frac{2\Gamma_1}{J_1 - j(\Gamma_1+\Gamma_2)}}\cos\theta_1
    +f_2\sqrt{\frac{2\Gamma_2}{J_2 + (j+1)(\Gamma_1+\Gamma_2)}}\cos\theta_2
      \right].
  \end{align}
#+END_SRC
@@latex:\noindent@@ We have $\Gamma_i \ll \Lambda_i$ for small
eccentricities.  Under this assumption, we may drop terms smaller than
$\mathcal{O}(\Gamma_i^2/\Lambda_i^4)$.  Equation eqref:eq:H01 becomes
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:H02}
    \mathcal{H}_0
    = -\frac{1}{(1+q)^3}\left[
       \frac{q^3}{2\Lambda_1^2} + \frac{1}{2\Lambda_2^2}
     + 2\left(
       \frac{jq^3}{\Lambda_1^3} - \frac{(j+1)}{\Lambda_2^3}
       \right)(\Gamma_1+\Gamma_2)
     -\frac32\left( 
       \frac{jq^3}{\Lambda_1^4} - \frac{(j+1)}{\Lambda_2^4}\right)
       (\Gamma_1+\Gamma_2)^2
       \right]
  \end{align}
#+END_SRC
@@latex:\noindent@@
and equation eqref:eq:Hpert1 reduces to its original form
#+BEGIN_SRC latex
  \begin{align}
  \label{eq:H_3}
    \mathcal{H}_{\rm pert}
    =-\frac{\tilde\mu}{(1+q)^2\Lambda_2^2}
    \left[
    f_1\sqrt{\frac{2\Gamma_1}{\Lambda_1}}\cos\theta_1
    +f_2\sqrt{\frac{2\Gamma_2}{\Lambda_2}}\cos\theta_2
    \right].
  \end{align}
#+END_SRC
@@latex:\noindent@@ Absent any dissipation, $\Lambda_1$ and
$\Lambda_2$ are approximately constant in resonance.  Hence, we may
drop the first two terms in parentheses in equation eqref:eq:H02,
leaving only the terms which include factors of $(\Gamma_1+\Gamma_2)$:
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:H03}
    \mathcal{H}_0
    = -\frac{1}{(1+q)^3}\left[
     2\left(
       \frac{jq^3}{\Lambda_1^3} - \frac{(j+1)}{\Lambda_2^3}
       \right)(\Gamma_1+\Gamma_2)
     -\frac32\left( 
       \frac{jq^3}{\Lambda_1^4} - \frac{(j+1)}{\Lambda_2^4}\right)
       (\Gamma_1+\Gamma_2)^2
       \right].
  \end{align}
#+END_SRC

Following cite:henrard86_reduc_trans_apocen_librat
[[citep:wisdom_canonical_1986][or equivalently][]], let $\v X$ be the
cartesian formulation
#+BEGIN_SRC latex
  \begin{align}
    \v X &= (x_1, x_2, X_1, X_2)\nonumber\\
    &= (\sqrt{\Gamma_1}\cos\theta_1, \sqrt{\Gamma_2}\cos\theta_2,
      \sqrt{\Gamma_1}\sin\theta_1, \sqrt{\Gamma_2}\sin\theta_2)
  \end{align}
#+END_SRC
@@latex:\noindent@@ 
Define
#+BEGIN_SRC latex
  \begin{align}
      g_1 &= f_1\sqrt{\frac{2}{\Lambda_1}} \\
      g_2 &= f_2\sqrt{\frac{2}{\Lambda_2}} \\
  \end{align}
#+END_SRC
@@latex:\noindent@@ and
#+BEGIN_SRC latex
  \begin{align}
    \mathcal{A} = \frac{1}{g_1\sqrt{g_1^2+g_2^2}}.
  \end{align}
#+END_SRC
@@latex:\noindent@@ The perturbation Hamiltonian $\mathcal H_{\rm
pert}$ becomes
#+BEGIN_SRC latex
  \begin{align}
    \mathcal H_{\rm pert} \propto g_1 x_1 + g_2 x_2
  \end{align}
#+END_SRC
@@latex:\noindent@@
Let $\v \Psi$ be the
counter-clockwise rotation by angle $\psi$ defined by $\tan\psi=
g_2/g_1$:
#+BEGIN_SRC latex
  \begin{align}
    \v \Psi =  \mathcal{A}
    \begin{pmatrix}
      g_1 & g_2 \\
      -g_2 & g_1 
    \end{pmatrix}.
  \end{align}
#+END_SRC
@@latex:\noindent@@ The block matrix
#+BEGIN_SRC latex
  \begin{align}
    \v M =
    \begin{pmatrix}
      \v \Psi & \v 0 \\
      \v 0 & \v \Psi
    \end{pmatrix}
  \end{align}
#+END_SRC
@@latex:\noindent@@ is symplectic citep:goldstein_classical_2000.
The coefficients $g_i$ depend weakly on the semimajor axis ratio
$\alpha$, and so $\v M$ only represents a canonical transformation if
$\alpha$ is stationary or varying slowly, which is a good
approximation for the systems considered in this paper.

Define the coordinates
#+BEGIN_SRC latex
  \begin{align}
     \v W = (w_1, w_2, W_1, W_2) \equiv \v M \v X.
  \end{align}
#+END_SRC
@@latex:\noindent@@ so that $w_1 = (g_1 x_1 + g_2 x_2)$.  Hence,
$\mathcal H_{\rm pert}\propto w_1$ only.  Finally, we revert the $\v
W$ set back to polar coordinates
$(\hat\theta_1,\hat\theta_2,S_1,S_2)$. The new resonance angle is
given by the equation
#+BEGIN_SRC latex
  \begin{align}
  \label{hattheta}
    \tan\hat{\theta}_1 = \frac{W_1}{w_1} = \frac{f_1 e_1\sin(\theta_1)
    + f_2e_2\sin(\theta_2)}{f_1e_1\cos(\theta_1) + f_2e_2\cos(\theta_2)}.
  \end{align}
#+END_SRC
@@latex:\noindent@@
and is conjugate to the momentum
#+BEGIN_SRC latex
  \begin{align}
    S_1 = w_1^2 + W_1^2 = f_1^2e_1^2
    + 2f_1f_2\cos(\varpi_1 - \varpi_2) + f_2^2e_2^2.
  \end{align}
#+END_SRC
@@latex:\noindent@@
It can be shown that
#+begin_src latex
  \begin{equation}
    \hat{\theta}_1 = (j+1)\lambda_2-j\lambda_1
    - \hat\varpi,
  \end{equation}
#+end_src
@@latex:\noindent@@
where
#+begin_src latex
  \begin{equation}
  \hat\varpi = \frac{\abs{f_1} e_1\sin(\varpi_1) -
    \abs{f_2}e_2\sin(\varpi_2)} {\abs{f_1}e_1\cos(\varpi_1) -
    \abs{f_2}e_2\cos(\varpi_2)}
  \end{equation}
#+end_src
@@latex:\noindent@@
We note that the other angle, $\hat\theta_2$,
is cyclic, and so its conjugate momentum $S_2$ is constant:
#+BEGIN_SRC latex
  \begin{align}
    S_2 = w_2^2 + W_2^2 = q\sqrt{\alpha}f_2^2e_1^2
  -2f_1f_2e_1e_2\cos(\varpi_1-\varpi_2) + \frac{f_1^2}{q\sqrt\alpha}e_2^2
  ,
  \end{align}
#+END_SRC
@@latex:\noindent@@
where $\alpha=a_1/a_2$ is the ratio of semimajor axes.
The sum
#+BEGIN_SRC latex
    \begin{align}
      \Gamma_1 +\Gamma_2 = x_1^2+x_2^2 + X_1^2 + X_2^2
      = w_1^2+w_2^2 + W_1^2 + W_2^2 = S_1 + S_2
    \end{align}
#+END_SRC
@@latex:\noindent@@
is preserved, and so the form of $\mathcal H_0(\Gamma_1+\Gamma_2)$
is preserved as well.

From here on out, we will denote $\hat\theta_1$ and $S_1$ as
$\hat\theta$ and $\hat S$ to indicate that they are the single pair of
dynamical variables.  We could just as well have carried out this
analysis with $\hat\theta_2$ and $S_2$, but $\hat S$ has the following
geometric interpretation:
#+BEGIN_SRC latex
  \begin{align}
    \hat S = \left\lvert \abs{f_1}\mathbf{e}_1 - \abs{f_2}\mathbf{e}_2\right\rvert^2,
  \end{align}
#+END_SRC
@@latex:\noindent@@
where the $\mathbf{e}_i$ are the Runge-Lenz vectors with magnitude
$e_i$ in the direction of $\varpi_i$.  

Altogether, we arrive at the following Hamiltonian after
dropping constant terms:
#+BEGIN_SRC latex
  \begin{align}
    \label{eq:HShat}\mathcal H(\hat \theta, \hat S) &= \mathcal H_0(\hat S) + \mathcal H_{\rm pert}(\hat \theta, \hat S) \\
    \mathcal H_0
    &= \left( 3\mathcal NS_2 -2\mathcal M\right) \hat S
      + \frac32 \mathcal N \hat S^2 \\
    \mathcal H_{\rm pert}
    &= - q\tilde\mu\mathcal K\sqrt{\hat S}\cos\hat\theta
  \end{align}
#+END_SRC
@@latex:\noindent@@ This form is valid for $q\in (0,\infty)$, and is
naturally extended to the case of an outer test particle by taking the
limit $q\to\infty$.  The extra factor of $q$ in front of $\mathcal K$
is so $q\tilde\mu$ reduces to $q\tilde\mu\to q\mu_2 \to \mu_1$ in the
$m_2=0$ test particle limit.  The coefficients in this case are given
by
#+BEGIN_SRC latex
  \begin{align}
    \mathcal M
    &= \frac{q^3}{(1+q)^3}\frac{j-(j+1)\alpha^{3/2}}{\Lambda_1^3}\\
    \mathcal N
    &= \frac{q^3}{(1+q)^3}\left(
      \frac{j}{\Lambda_1} - \frac{(j+1)\alpha^{3/2}}{\Lambda_2}
      \right)\frac{1}{\Lambda_1^3}\\
    \mathcal K
    &= \frac{q^2}{(1+q)^2}
      \frac{\alpha^{3/2}\Lambda_2}{f_1^2\sqrt{1+\alpha^{1/2}f_1^2/f_2^2}\Lambda_1^{5/2}}.\\
  \end{align}
#+END_SRC
A similar representation of $\mathcal H, \mathcal M$, $\mathcal N$,
and $\mathcal{K}$ also exists for which the limit $q\to 0$ converges
to the case of an inner test particle by exchanging the necessary
factors of $q$ for $\Lambda_1/\Lambda_2 = q\sqrt\alpha$.


*** Second fundamnetal model of resonance
Now, all that is left to do is to rescale equation eqref:eq:HShat
into what is referred to as
the "second fundamental model of resonance" citep:henrard_second_1983.



@@latex:\note{
Now transform into $\hat R$
}@@


** Elliptic restricted 3 body problem

@@latex:\twocolumn@@
bibliography:references.bib
bibliographystyle:mnras
