* preamble                                                           :ignore:
#+TITLE: Architecture of Planetary Systems in Mean Motion Resonance
#+OPTIONS: author:nil date:nil toc:nil
#+LATEX_CLASS: mnras
#+latex_header: \usepackage{caption}
#+latex_header: \usepackage{subcaption}
#+latex_header: \usepackage{pdfpages}
#+latex_header: \usepackage{float}
#+latex_header: \usepackage{booktabs}
#+latex_header: \usepackage{enumitem}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage{tensor}
#+latex_header: \usepackage{ wasysym }
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{xcolor}
#+latex_header: \usepackage{cancel}
#+latex_header: \newcommand{\note}[1]{{\color{red} \large #1 }}
#+latex_header: \renewcommand{\O}{\mathcal{O}}
#+latex_header: \renewcommand{\d}{\partial}
#+latex_header: \renewcommand{\v}[1]{\boldsymbol{ #1 }}
#+latex_header: \renewcommand{\t}[1]{\tilde{ #1 }}
#+latex_header: \newcommand{\tg}{\t{g}}
#+latex_header: \newcommand{\vh}[1]{\hat{\boldsymbol{ #1 }}}
#+latex_header: \newcommand{\pp}[2]{\frac{\partial #1}{\partial #2}}
#+latex_header: \newcommand{\dd}[2]{\frac{d #1}{d #2}}
#+latex_header: \DeclarePairedDelimiter{\abs}{|}{|}
#+latex_header: \DeclarePairedDelimiter{\norm}{||}{||}
#+latex_header: \DeclarePairedDelimiter{\p}{(}{)}
#+latex_header: \DeclarePairedDelimiter{\we}{\langle}{\rangle}
#+latex_header: \title[MMR Architecture]{Architecture of Planetary Systems in Mean Motion Resonance}
#+latex_header: \author[Laune et al.]{
#+latex_header: JT Laune,$^{1}$
#+latex_header: Laetitia Rodet,$^{1}$
#+latex_header: and Dong Lai$^{1}$
#+latex_header: \\
#+latex_header: $^{1}$Department of Astronomy and Space Sciences, Cornell University\\}

#+begin_src latex
\maketitle
#+end_src

* Introduction

Early in a planetary system’s life, the orbits of newly formed planets
are likely constantly changing.  Interactions with the gaseous and
dusty protoplanetary disks (PPDs) exert a negative torque on the
embedded planet, which leads to angular momentum loss and subsequent
contraction of the planet’s semimajor axis
cite:nelson_planetary_2018. This process is collectively known as
planetary migration.

When two planets' periods are related by an integer fraction $p$:$q$
(e.g. 2:1, 3:2), mutual gravitational interactions can lock orbits
into mean motion resonances (MMRs).
If the integers $p,q$ differ by one, i.e. $j$:$j+1$ for some $j$,
the gravitational interactions are first order in eccentricity
and inclination.
The resonance angles for first order MMRs are given by
#+BEGIN_SRC latex
  \begin{align}
  \label{circangles}
   \theta_1 &= (j+1)\lambda_2 - \lambda_1 - \varpi_1 \\
   \theta_2 &= (j+1)\lambda_2 - \lambda_1 - \varpi_2.
  \end{align}
#+END_SRC
The mean longitudes of the inner and outer planets are denoted by
$\lambda_1$ and $\lambda_2$, respectively, and $\varpi_1$ and
$\varpi_2$ denote their longitudes of perihelion.  If the angles
$\theta_1$ and $\theta_2$ librate around $\pi$ and $0$, respectively,
the system is said to be in resonance.  As a planet migrates, its
resonance locations sweep across the disk along with it and capture
planets into resonant pairs and chains.
While in resonance, torques from the gas damp the
system's angular momentum deficit (AMD) into equilibrium.  The MMR
equilibrium is governed by various conditions which are well studied
in the literature
cite:henrard_second_1983,deck_migration_2015,goldreich_overstable_2014,xu_migration_2018,henrard_second_1983.
The resonant pair's path across the disk determines the final orbital
architecture for the system
cite:cresswell_evolution_2006,cresswell_three-dimensional_2008.

In recent years, thousands of exoplanet systems have been discovered,
and, although many resonant systems have been found, the proportion of
such systems is low compared to theoretical expectations based on disk
migration cite:fabrycky_architecture_2014.  In addition to the paucity
of planets in MMRs, there also seems to be an overabundance of planets
just outside of mean motion resonances, with period ratios slightly
larger than 2 or 3/2
cite:fabrycky_architecture_2014,choksi_sub-neptune_2020.
A system's orbital architecture can reveal details about its history.
Commensurate period ratios may indicate past resonant interactions
within the planetary system, but the present state of the resonance
can only be determined by analyzing the behavior of the angles in
equation eqref:circangles.  Furthermore, since these angles are
related by $\theta_2-\theta_1=\gamma_1-\gamma_2$, this implies that a
resonant pair of planets will be apsidally anti-aligned.

NASA's \emph{K2} mission initially discovered the planets K2-19b and c
near a 3:2 period ratio ($P_b=7.9$ d, $P_c=11.9$ d), and later on
planet K2-19d at $P_d=2.5$ d
cite:howell14_k2_mission,armstrong15_one_closes_exopl_pairs_to,sinukoff16_eleven_multip_system_fromk_masses.
Both planets had moderate eccentricities $e_b\approx e_c\approx 0.2$.
Further observations revealed K2-19b and c to be \emph{aligned}, with
$\Delta\varpi\equiv \varpi_c-\varpi_b \approx 2\pm 2$
cite:petigura_k2-19b_2020.  Hence, the K2-19 system poses a problem
for the conventional understanding of planet migration and resonance
capture.

Understanding the genesis of extrasolar orbital configurations, and
their corresponding observational implications, offers us an insight
into the history of the system.  In this paper, we review the
analytically simple migration model commonly used in the literature.
In Section [[Planet Migration]], we modify the model slightly and explore
a wider parameter space for the coupling between the resonant
eccentricities and the protoplanetary disk. We fail to find any disk
conditions which robustly lead to apsidal alignment.  In Section
[[Apsidal Alignment]], we design a toy model for driving eccentricity and
explain how it may explain the apsidal alignment between K2-19b and
c. We demonstrate that the orbital architecture of K2-19 can be
explained by an external force which pumps the eccentricities beyond
their equilibrium values.

* Planet Migration
*** Dissipative forces                                             :ignore:
Planets embedded within a protoplanetary disk interact gravitationally
with the gas and lose angular momentum, leading to inward migration
towards the central star.  Disk torques vary with planet mass as well
as across semimajor axis; large outer planets lose angular momentum
quickly and sweep up inner planets into MMRs
cite:tanaka_three-dimensional_2004,xu_migration_2018.  In some
cases, the planet can gain angular momentum and migrate away from the
primary.

In this paper, we will ignore the detailed physics of
planet-disk interactions and instead implement dissipative forces
parametrized by the eccentricity damping and migration timescales,
denoted by $T_{e,i}$ and $T_{m,i}$ for $i=1,2$. The accelerations are
then given by:
#+begin_src latex
  \begin{align}\label{eq:disforce}
    \frac{\dot{e}_i}{e_i} &= -\frac{1}{T_{e,i}} \\
    \frac{\dot{a}_i}{a_i} &= -\frac{1}{T_{m,i}} -\frac{2e_i^2}{T_{e,i}}.
  \end{align}
#+end_src
In our notation, $T_{m,i}>0$ $(<0)$ denotes inward (outward)
migration.  For typical, thin disk profiles, we have
cite:tanaka_three-dimensional_2004,cresswell_three-dimensional_2008,xu_migration_2018
#+BEGIN_SRC latex
  \begin{align}
    \frac{T_{e,1}}{T_{e,2}}&= \frac1q\\
    T_{e,i}&=3.46 h^2 T_{m,i}.
  \end{align}
#+END_SRC
To scale the dissipation times in the integrations, we choose
a parameter $T_{e,0}$ and set
#+BEGIN_SRC latex
  \begin{align}
    T_{e,1}&=T_{e,0}\sqrt{q}\\
    T_{e,2}&= T_{e,0}/\sqrt{q}.
  \end{align}
#+END_SRC
We must have $1/T_{m,1} - 1/T_{m,2} > 0$ for convergent
(i.e. $\abs{a_1-a_2}$ is shrinking) inward migration, and vice versa
for outward migration. Hence, for $q>1$, we set $T_{m,i}< 0$; for
$q<1$, we set $T_{m,i}>0$.  Unless noted otherwise, we choose $h=0.1$
and $T_{e,0}=1000~\rm{years}$.  We'll refer to these relationships as
the "standard picture" of planet migration. Similar models are
commonly used in the literature
cite:deck_migration_2015,xu_migration_2018,goldreich_overstable_2014.

** MMR
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{./standard-example-h-0.1-Tw0-1000}.png}
    \caption{Standard MMR capture process for $h=0.1$ and $q=2$. The
      outer planet $m_2$ starts wide of resonance and is captured near
      $t=2000$ yrs, after which the two angles $\theta_1\to180^\circ$
      and $\theta_2\to 0^\circ$.  While in resonance, the $e_i$ values
      are driven to equilibrium and the periapses are antialigned.}
    \label{fig:standardex}
  \end{figure*}
#+END_SRC

*** MMR                                                            :ignore:
When two planets have commensurate period ratios, $p$:$q$ where $p,q$
are integers, their gravitational interactions may lock them into a
mean motion resonance (MMR).  As young planets migrate within their
disk, if the migration is convergent, they
cross MMR period ratios and may be captured. In our paper, we will be
considering only first order MMRs, denoted by $j$:$j+1$, which occur
where $n_2/n_1 = j/j+1$, where $n_1,n_2$ denote the inner and outer
planet, respectively.

The Hamiltonian of a system with two planets near a first order MMR is
cite:murray_solar_2000:
#+BEGIN_SRC latex
  \begin{align}
  \label{hamiltonian}
    H_{\rm kep} = & -\frac{G M m_{1}}{2 a_{1}}-\frac{G M m_{2}}{2 a_{2}}\nonumber\\
    H_{\rm res} = & -\frac{G m_{1} m_{2}}{a_{2}}
                    \left[
                    f_{1} e_{1} \cos \theta_{1} 
                    +f_{2} e_{2} \cos \theta_{2}\right]\nonumber\\
    H_{\rm sec} = &-\frac{G m_{1} m_{2}}{a_{2}}\left[f_{3} (e_1^2 + e_2^2)
                    +f_4e_1e_2\cos(\varpi_2-\varpi_1)
                    \right] \nonumber\\
    H = &~ H_{\rm kep} + H_{\rm res}+ H_{\rm sec}. 
  \end{align}
#+END_SRC

$H_{\rm kep}$ is the standard Keplerian Hamiltonian; $H_{\rm res}$
the resonant interactions between the planets of order
$\O(e_i)$; and $H_{\rm sec}$ the secular interactions.
The two angles are given as in eqref:circangles.

Equation eqref:hamiltonian admits eight coupled ODES ($\dot a_i, \dot
e_i, \dot\theta_i, \dot\varpi_i$), which we may integrate together
with the effects of dissipation to simulate MMR capture.  An example
of MMR capture is given in Figure ref:fig:standardex.  The period
ratio $P_2/P_1$ initially starts wide of the nominal resonance value
of $1.5$.  After around $2~\rm{kyr}$ of convergent migration, the
planets are caught into MMR, indicated by the stabilization of
$\theta_1$ to $180^\circ$ and $\theta_2$ to $0^\circ$.  The planets'
eccentricities level off at around $4~\rm{kyr}$ near $e_1\approx 0.02$
and $e_2\approx0.04$, and the planets become apsidally anti-aligned
with $\varpi_1-\varpi_2\approx 180^\circ$.

In this paper, we will use the term "resonance" loosely to mean the
libration of an angle such as $\theta_1$, $\theta_2$, and later on
$\hat\theta$.  We'll also use the angle itself to refer to the
resonance, i.e. the planets $m_1$ and $m_2$ in Figure
ref:fig:standardex are caught into both $\theta_1$ and $\theta_2$,
respectively, since those angles are librating.

During the migration phase, planets typically retain small
eccentricities. Indeed, the standard circular MMRs (angles $\theta_1$
and $\theta_2$) have finite resonance widths in $e$, and so small
eccentricities are necessary for capture.  Most studies consider only
the resonant terms for this reason, since they are first order in
eccentricity.  However, if eccentricities are excited, secular terms
play an important role, and so we keep them.

** Equilibrium
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \begin{subfigure}[t]{0.225\textwidth}
    \includegraphics[width=1\textwidth]{{standard-eeqs-Tm2--40873-Tw0-1000}.png}
    \caption{ }
    \label{fig:standardeqecc}
    \end{subfigure}
    \begin{subfigure}[t]{0.225\textwidth}
    \includegraphics[width=1\textwidth]{{standard-pomega-Tm2--40873-Tw0-1000}.png}
    \caption{ }
    \label{fig:standardDpom}
    \end{subfigure}
    \caption{\emph{(a)} Analytical equilibrium values are plotted
      as dashed lines for various values of $q$. The points
      indicate time averaged numerical results from integrating the
      time-dependent equations of motion.  Error bars indicate the
      standard deviation of the eccentricities; most fall within
      the marker for eccentricity.  Simulations without secular
      effects showed only negligible differences, and so they were
      not included.  \emph{(b)} Same as \emph{(a)}, but for
      $\Delta\varpi$. Simulations without secular effects did show
      significant differences, and so they have been included.}
  \label{fig:standard}
  \end{figure}
#+END_SRC

*** Equilibrium                                                    :ignore:
The MMR capture in Figure ref:fig:standardex reaches an equilibrium
state in period ratio, resonant angles, eccentricities, and
$\Delta\varpi$.  Indeed, the Hamiltonian in equation
[[eqref:hamiltonian]], including the dissipative terms, admits the
following three equations for equilibrium values of
$(e_1,e_2,\theta_1,\theta_2)$:
#+begin_src latex
  \begin{equation}
  \label{dote1}
    \dot e_1 = \frac{\mu_2}{\alpha_2} [f_1\sin(\theta_1) - De_2 \sin(\gamma_2-\gamma_1)] - \frac{e_1}{T_{e,1}}=0
  \end{equation}
  
  \begin{equation}
  \label{dote2}
    \dot e_2 = \frac{q\mu_2}{\alpha_2} [f_2\sin(\theta_2) - De_1 \sin(\gamma_1-\gamma_2)]- \frac{e_2}{T_{e,2}}=0
  \end{equation}
  
  \begin{align}
  \label{dotdpom}
    \frac{d}{dt}\Delta\varpi \equiv \dot\varpi_1-\dot\varpi_2
    &= \frac{\mu_2}{\alpha_2} \left[ \frac{f_1\cos\theta_1}{\alpha_1^{1/2} e_1}
       - \frac{qf_2\cos\theta_2}{\alpha_2^{1/2}e_2}\right.\nonumber \\
    &\quad+ \left.\frac{2C}{\alpha_1^{1/2}} + \frac{De_2}{\alpha_1^{1/2} e_1}
      - \frac{2qC}{\alpha_2^{1/2}} - \frac{qDe_1}{ \alpha_2^{1/2}e_2}\right]=0
  \end{align}
#+end_src
where we have combined $\Delta\varpi = \theta_2 - \theta_1 =
\varpi_1-\varpi_2$ in the last equation.

We must find a fourth equation to complete this system of equations.
Absent any dissipative or secular forces, the following quantities are
conserved:
#+begin_src latex
  \begin{align}
    J &= \Lambda_1\sqrt{1-e_1^2} + \Lambda_2\sqrt{1-e_2^2}\\
    G &= \frac{j+1}{j} \Lambda_1 + \Lambda_2.
  \end{align}
#+end_src
The quantity $J$ is the angular momentum of the system, and $G$ is an
integral of motion for the the Hamiltonian $H_{\rm kep}+H_{\rm res}$
in equation eqref:hamiltonian.  Define $\eta$ to be the ratio of $J$ and $G$,
#+begin_src latex
  \begin{align}
    \eta(\alpha, e_1, e_2) &\equiv - 2(q/\alpha_0+1)\p*{\frac{J}{G}-\left.\frac{J}{G}\right|_{0}},
  \end{align}
#+end_src
where $\alpha_0 = (j/(j+1))^{3/2}$ and $\left(J/G\right|_{0}$ is
evaluated at $e_i=0$ and $\alpha=\alpha_0$.
Thus, we have $\eta(\alpha_0, 0, 0)=0$ and the corresponding Taylor expansion yields
#+begin_src latex
  \begin{align}
    \eta \approx -\frac{q(\alpha-\alpha_0)}{j\sqrt{\alpha_0}(q/\alpha_0+1)} + q\sqrt{\alpha_0}e_1^2 + e_2^2
  \end{align}
#+end_src

The equation of motion for $\eta$ is then given by
#+begin_src latex
  \begin{align}
  \label{doteta}
    \dot\eta = \frac{q\alpha_0^{1/2}}{j(q\alpha_0^{-1}+1)}&\left[ \frac{1}{T_{m2}} - \frac{1}{T_{m1}}
        + \frac{2e_1^2}{T_{e1}}- \frac{2e_2^2}{T_{e2}} \right] \nonumber\\
      &- q\alpha_0^{1/2}\frac{2e_1^2}{T_{e1}} - \frac{2e_2^2}{T_{e2}}=0.
  \end{align}
#+end_src
We note that the only contribution to $\dot{\eta}$ is from dissipative effects.

By solving the four equations [[eqref:dote1]] -- eqref:dotdpom and
[[eqref:doteta]] , we may arrive at equilibrium values for the system.  In
the standard picture and neglecting secular terms (i.e., for small
$e_i$), equations [[eqref:dote1]] and [[eqref:dote2]] show
$\sin(\theta_i)\approx 0$.  Equation [[eqref:dotdpom]] then gives us
$\theta_1\approx \pi$ and $\theta_2\approx 0$.  Since
$\theta_1-\theta_2 = \varpi_2-\varpi_1$, we therefore see that
convergent migration produces anti-aligned periapses.  We confirm this
in the time-dependent integration in Figure ref:fig:standardex.

*** Standard model                                                 :ignore:
The equilibrium $e_i$'s and $\Delta\varpi$'s for comparable mass
planets $(q\in[0.5,2])$ are given in Figures ref:fig:standardeqecc and
[[ref:fig:standardDpom]].  Analytical solutions to the equilibrium
equations are plotted as dashed lines.  Here we also integrate the
time-dependent differential equations from Hamiltonian
eqref:hamiltonian and plot the average $e_1$, $e_2$, and
$\Delta\varpi$ over the last 10% of the timespan.  These results are
calculated with outward migration for $q>1$ and inward migration for
$q<1$.

As we can see, the final averaged eccentricities for $m_1$ and $m_2$
go approximately as $e_1/e_2 \sim q$. As expected, the $\Delta\varpi$
average values are all very close to $\pi$. The numerical and
analytical results largely agree.  In the next two sections, we will
explore slightly modified models by varying the ratio
$T_{e,1}/T_{e,2}$ within $[0.1q, 10q]$.

** Eccentricity damping timescales
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.3\textwidth]{{./varyTe-eeqs-h-0.1-Tw0-1000}.png}
    \caption{ Equilibrium eccentricity values for a range of
      $T_{e,1}/T_{e,2}\in[0.2,10]$ are plotted for three
      different values of $q=0.5,1.0,$ and $2.0$. The points and
      errorbars are calculated in the same way as
      \ref{fig:standard}.  The dashed lines indicate analytical
      estimates for $e_i$.}
    \label{fig:eqecc}
  \end{figure}
#+END_SRC

#+BEGIN_SRC latex
  \begin{figure}
    \centering
    \includegraphics[width=0.3\textwidth]{{./varyTe-pomega-h-0.1-Tw0-1000}.png}
    \caption{Same as \ref{fig:eqecc} but for $\Delta\varpi$.}
    \label{fig:eqDpom}
  \end{figure}
#+END_SRC
*** Damping Timescales                                             :ignore:
Up until now, we have strictly been considering the standard picture
of planet migration -- with $T_{e,1}/T_{e,2} = 1/q$ and
$T_{e,i}=3.46h^2T_{e,i}$ -- which always gives rise to apsidal
anti-alignment for reasonable disk conditions.  This simple
parametrized model will always fail to capture all of the complicated
hydrodynamics of real astrophysical disks. We can therefore easily
expect a difference in the ratio $T_{e,1}/T_{e,2}$ over an order of
magnitude, and perhaps this modfication could produce
$\Delta\varpi\approx0^\circ$ without adding new parameters to the
model.

We explore this possibility in Figures ref:fig:eqecc and
ref:fig:eqDpom. The ratio $T_{e,1}/T_{e,2}$ varies freely between
$0.2$ and $10$, regardless of the mass ratio.  Initially, we attempted
to extend this range to $T_{e,1}/T_{e,2}=0.1$, but the system
eventually escapes resonance for all $q=0.5$, $1$, and $2$ and no
equilibrium is reached.  The migration timescales are set to
$\abs{T_{m,i}}=T_{e,i}/3.46 h^2$.  For $T_{e,1}<T_{e,2}$, then, we set
$T_{m,i}>0$, corresponding to outward migration, and vice versa for
$T_{e,1}>T_{e,2}$.

For comparable mass planets with $q=0.5$, $1$, and $2$, varying the
ratio $T_{e,1}/T_{e,2}$ around $1/q$ modifies the final equilibrium
eccentricities by a roughly similar factor, as seen in Figure
ref:fig:eqecc. The eccentricity ratio $e_1/e_2$ is largely unchanged,
yet the magnitudes $e_1$ and $e_2$ are larger for more extreme values
of $T_{e,1}/T_{e,2}$.  The dashed lines plot the analytic results from
solving equations [[eqref:dote1]] -- [[eqref:doteta]]; these findings
reproduce the numerical results.

The corresponding values for $\Delta\varpi$ are shown in
ref:fig:eqDpom. Variations in the eccentricity damping ratio cannot
account for apsidal alignment.  In all cases, the analytic equilibrium
equations predict $\Delta\varpi\approx 180^\circ$, and the numerical
integrations agree.  We note that the equilibrium solutions given in
Figures ref:fig:standard - ref:fig:eqDpom are not continuous across
the line $T_{e,1}/T_{e_2} = 1$ (i.e. $q=1$ in ref:fig:standard), which
is where we reverse the migration direction to ensure it is
convergent.

* Apsidal Alignment
As we have seen, capture into the $\theta_1$ and $\theta_2$ resonance
always leads to $\Delta\varpi=180^\circ$ due to their equilibrium
values being $180^\circ$ and $0^\circ$, respectively.  The apsidally
anti-aligned K2-19 system therefore poses a problem for our standard
model.  In order to match this observation, either $\theta_1$,
$\theta_2$, or both angles must cease to be in resonance.

** Eccentricity driving forces
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{driving-example-h-0.03-Tw0-1000}.png}
    \caption{Here we have set $e_{2,d}=0.3$ with $h=0.1$ and $q=2$.  After
      about 10~kyr, the system escapes the circular resonances and becomes
      apsidally aligned.}
    \label{fig:drivingex}
  \end{figure*}
#+END_SRC
*** forces                                                         :ignore:
One way of escaping the circular $\theta_i$ resonances is to
artificially drive the eccentricity of the system to larger values,
where $\theta_i$ will cease to act.  We modify the eccentricity
damping for $m_2$ in eqref:eq:disforce to be
#+begin_src latex
  \begin{equation}
    \frac{\dot e_2}{e_2} = -\frac{(e_2-e_{2,d})}{T_{e,2}}.
  \end{equation}
#+end_src
Hence, planet $m_2$ is exponentially driven to $e_{2,d}$ with a
timescale of $T_{e,2}$.  In Figure ref:fig:drivingex, we demonstrate
the feasibility of this approach, where we have added in the driving
force with $e_{2,d}=0.3$ by hand and set $q=2$.  We initalize the
system close to resonance, where it stays for around 8,000
years. Between $t=8,000$ and $10,000$ years, $e_1$ and $e_2$ grow and
the system subsequently breaks out of both the $\theta_1$ and
$\theta_2$ resonances.  At this point, both planets' ecentricities are
excited to about $e_i\approx 0.2$ and the planets become apsidally
aligned as $\Delta\varpi$ librates around $0^\circ$ with an amplitde
of around $100^\circ$.
** Reducing the Hamiltonian
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{./phasediag}.png}
    \caption{\emph{Left}: Equilibrium points for the Hamiltonian in
      equation (\ref{hhat}) for various values of $\delta$ are
      plotted in black.  The green lines indicate the $\delta$ values
      used for the right two phase diagrams, along with their
      associated equilibria.  The resonance zone for $\delta>0$ is
      shaded in red.  \emph{Middle}: Phase diagram for
      $\delta=-0.5$. There is only a single equilibrium and resonance
      zone to the right of the origin.  \emph{Right}: Phase diagram
      for $\delta= 1$. There are three equilibria; the separatrix
      passes through the leftmost equilibrium point, which is a
      saddle point in phase space. The small lobe of the separatrix
      encloses a circulation zone with a stable equilibrium near the
      origin. The leftmost equilibrium point is located within the
      resonance zone in between the two lobes of the separatrix.}
    \label{fig:phasediag}
  \end{figure*}
#+END_SRC
#+BEGIN_SRC latex
    \begin{figure}
      \centering
      \includegraphics[width=0.4\textwidth]{{./Rhat-grid}.png}
      \caption{\emph{Left:} 
  \emph{Right:}}
      \label{fig:Rhat-grid}
    \end{figure}
#+END_SRC
*** Hhat                                                           :ignore:
A detailed analysis of the MMR Hamiltonian eqref:hamiltonian
illustrates the underlying dynamics behind the capture processes in
Figure ref:fig:drivingex which lead to apsidal alignment.  Following
cite:henrard86_reduc_trans_apocen_librat (or equivalently
cite:wisdom_canonical_1986), we may transform the Hamiltonian $H_{\rm
Kep} + H_{\rm res}$ in equation [[eqref:hamiltonian]] into the form
#+begin_src latex
  \begin{equation}
    \label{hhat}
    \hat H(R,\hat\theta) = -3(\delta+1) R + R^2 - 2\sqrt{2 R} \cos(\hat\theta)
  \end{equation}
#+end_src
through a series of rotations in phase space.  Consider the phase
space configuration $\v\xi=(\theta_1, \theta_2, \Gamma_1, \Gamma_2)$,
where the $\Gamma_i$ are the $\text{Poincair\'e}$ momenta
$\Gamma_i=\Lambda_i(1-\sqrt{1-e_i^2})$.
Let $\v X$ be the cartesian
formulation
#+BEGIN_SRC latex
  \begin{align}
    \v X &= (x_1, x_2, X_1, X_2)\nonumber\\
    &= (\sqrt{2\Gamma_1}\cos\theta_1, \sqrt{2\Gamma_2}\cos\theta_2,
      \sqrt{2\Gamma_1}\sin\theta_1, \sqrt{2\Gamma_2}\sin\theta_2)
  \end{align}
#+END_SRC
The resonant Hamiltonian becomes
\[ H_{\rm res} \propto f_1 x_1 + f_2 x_2 \]

Let $\v \Psi$ be the
counter-clockwise rotation by angle $\psi$ defined by $\tan\psi=
f_1/f_2$:
#+BEGIN_SRC latex
  \begin{align}
    \v \Psi = \frac{1}{f_2\sqrt{f_1^2+f_2^2}} 
    \begin{pmatrix}
      f_2 & f_1 \\
      -f_1 & f_2 
    \end{pmatrix}.
  \end{align}
#+END_SRC
The block matrix
#+BEGIN_SRC latex
  \begin{align}
    \v M =
    \begin{pmatrix}
      \v \Psi & \v 0 \\
      \v 0 & \v \Psi
    \end{pmatrix}
  \end{align}
#+END_SRC
is symplectic cite:goldstein_classical_2000.  The Laplace coefficients
$f_i$ depend weakly on the semimajor axis ratio $\alpha$, and so $\v
M$ only represents a canonical transformation if $\alpha$ is
stationary or varying adiabatically, which is a good approximation
for the systems considered in this paper.

Define the coordinates
#+BEGIN_SRC latex
  \begin{align}
    \v W = \v M \v X.
  \end{align}
#+END_SRC

Somewhat 

The canonical coordinate $\hat{\theta}$ is given by the equation
#+BEGIN_SRC latex
  \begin{align}
  \label{hattheta}
    \tan\p*{\pi-\hat{\theta}} = \frac{e_1\sin(\theta_1)
    + (f_2/f_1)e_2\sin(\theta_2)}{e_1\cos(\theta_1) + (f_2/f_1)e_2\cos(\theta_2)},
  \end{align}
#+END_SRC
where we have included a shift by $\pi$ so that $\hat{\theta}$ has an
equilibrium value at $0$ rather than $\pi$.

We define $\v{\hat e} = \abs{f_1}\v e_1 - \abs{f_2}\v e_2$ so that
the conjugate momentum $R$ is
#+begin_src latex
  \begin{equation}
    R \propto \norm{\v{\hat e}}^2  = f_1^2e_1^2 - 2\abs{f_1f_2}e_1e_2\cos(\varpi_1-\varpi_2) + f_2^2e_2^2
  \end{equation}
#+end_src
where $\v e_i$ is the Runge-Lenz vector, i.e. the vector with
magnitude $e_i$ in the direction of perihelion. The true value
includes total scaling factors such as $\mu_{\rm tot}$. For our
purposes, $\v{\hat e}$ will suffice.

For the case $e_1=0$ and $\mu_2\ll\mu_1$, the system's conjugate
momentum takes the form $R\sim e_1^2$ with coordinate $\hat \theta =
\theta_1$, and vice versa for $e_2=0$, $\mu_1\ll\mu_2$.  These parameters
describe the standard scenario of a test particle near an MMR with a
massive planet on a circular orbit, the derivation of which may be
found in cite:murray_solar_2000. The parameter $\delta$ describes the
system's depth into resonance.

Since the canonical momenta of the circular angles $\theta_i$ have
$R_i\propto e_i^2$, resonance capture widths $\delta a_i$ are
functions of $e_i$ as well. Hence, for large eccentricities near the
resonance location, $m_1$ and $m_2$ may not be captured into
resonance. However, if we consider the Hamiltonian system $H_{\rm
Kep} + H_{\rm res}$ in eqref:hamiltonian as a whole, i.e. considering
$m_1$ and $m_2$ simultaneously, there is one resonance angle
$\hat\theta$ that describes the system's dynamics which may operate
separately from $\theta_1$ and $\theta_2$.


The resonant equation of motion for $R$ is
#+begin_src latex
  \begin{equation}
    \dot R_{\rm res} = -\frac{\d \hat H}{\d \hat\theta} = -2\sqrt{2R}\sin(\hat\theta) = 0
  \end{equation}
#+end_src
in resonance.  Hence, only dissipative and secular forces are at play
if $\hat\theta$ is operating.  The integrations in Figures
ref:fig:drivingex and ref:fig:e0large do not show qualitative
differences if the secular terms are turned off, and so the apsidal
alignment must be due to dissipation. If we assume the semimajor axis
ratio is constant and consider only the dissipative effects on $R$, we
arrive at the following relation for equilibrium in $R$:
#+begin_src latex
  \begin{equation}
    \label{eq:diseqR}
    \cos\Delta\varpi \sim \frac{e_1^2 T_{e,2} + e_2^2 T_{e,1}}{e_1e_2(T_{e,1}+T_{e,2})}.
  \end{equation}
#+end_src
For reasonable disk parameters ( $h\sim 0.1$, $T_{e,i}\sim h^2
T_{m,i}$ ), the right hand side of equation eqref:eq:diseqR
is order unity, and so we see that $\Delta\varpi\approx 0$.


The Hamiltonian in [[eqref:hhat]] is known as ``the second fundamental
model of resonance''. Its phase space is well studied in the
literature, so we will only review it briefly, following the approach
in cite:henrard_second_1983.  The choice of polar coordinates in
equation [[eqref:hattheta]] introduces a virtual singularity at $R=0$
cite:henrard_second_1983.  If we switch to the canonical Cartesian
coordinates $\xi = \sqrt{R}\cos\theta$ and $\nu = \sqrt{R}\cos\theta$,
$\hat H$ becomes

#+begin_src latex
  \begin{equation}
    \hat H(\xi,\nu) = -3(\delta+1)(\xi^2+\nu^2) + (\xi^2+\nu^2)^2 -2\sqrt2
    \xi
  \end{equation}
#+end_src

In equilibrium, $\dot R = \d\hat H/\d\theta \propto \sin\theta= 0$,
and so we see that equilibria must lie along the line $\nu=0$ in phase
space.  The left panel of Figure ref:fig:phasediag displays the
results of solving the equation $\hat H(\xi, 0) = 0$ for $\xi$
numerically for various values of $\delta$.  For $\delta<0$, there is
one equilibrium point to the right of the origin; for $\delta \geq 0$,
a separatrix appears which divides the phase space into 3 regions:
outer circulation (outside the separatrix), inner circulation (within
the inner lobe of the separatrix), and the resonance zone (between the
inner and outer lobe of the separatrix).  The resonance zone is
indicated in red in the left panel of Figure ref:fig:phasediag.  The
right two panels of Figure ref:fig:phasediag display the phase space
for choices of positive and negative $\delta$.

** Phase space paths
*** figures                                                        :ignore:
#+BEGIN_SRC latex
      \begin{figure*}
        \centering
        \includegraphics[width=0.5\textwidth]{{./relative-geometry}.png}
        \caption{ }
        \label{fig:relgeom}
      \end{figure*}
#+END_SRC
*** phase space                                                    :ignore:

In ref:fig:phasediagsex, we display the phase spaces from all three
integrations plotted in the previous sections.
The top row displays the $(\theta_2, \propto e_2)$ conjugate pair.
The standard setup enters a tight resonance quickly and stays there (indicated by the small yellow region).
Driving $e_2$ to a value $e_{2,d}=0.3$ leads to an early libration, indicated by the blue-green inner lobe.
The planet $m_2$ then enters the outer circulation region and reaches equilibrium.
On the contrary, the simulation with both $e_1 = e_2 = 0.2$ starts well outside the separatrix (purple).
Dissipative forces push the system closer to the separatrix; then, the disk forces cease
and the system remains in the circulation region. This way, the system never enters the $\theta_2$
resonance. The $\theta_1$ resonance is similar.

On the other hand, the bottom row of ref:fig:phasediagsex displays the
phase space for $(\hat\theta,\propto \hat e)$.
All three systems end up in resonance. The standard picture is a very tight resonance, while the
$e_2$ -driving and large $e_0$ systems enter stable libration in the resonance zone.
The two apsidally aligned cases therefore end up in analagous phase space configurations, but
through different dynamical paths.

* Conclusion

#+begin_src latex
  \clearpage
#+end_src

* Appendix
** Elliptic restricted 3 body problem

bibliography:references.bib
bibliographystyle:apalike
