#+BEGIN_SRC latex
      \begin{figure*}
        \centering
        \includegraphics[width=0.7\textwidth]{{./phasediagsex}.png}
        \caption{ Here we have plotted each example runs' path through
          phase space. On the top row, we plot only the
          $e_2\longleftrightarrow\theta_2$ resonance to save space; the
          $e_1\longleftrightarrow\theta_1$ resonance is similar.  Time is
          indicated by color, with purple near $t=0$ and yellow near the
          end of the simulation. All times are scaled to the beginning
          and end times of the integration for comparison, not physical
          time.  \emph{Left:} The standard example. Here we see both the
          $\theta_2$ and $\hat\theta$ resonances are
          acting. \emph{Middle:} The case with eccentricity driving
          forces.  The system starts near the origin in $(e_2,\theta_2)$
          space, and moves outwards to the circulation zone due to the
          driving forces.  \emph{Right:} Similar to the driving force
          case, but this time the system starts well outside of the
          resonance zone in $(e_2,\theta_2)$ space and then gets trapped
          into the circulation zone due to dissipative forces.  }
        \label{fig:phasediagsex}
      \end{figure*}
#+END_SRC

#+BEGIN_SRC latex
  \begin{figure*}[htb]
    \centering
    \includegraphics[width=0.95\textwidth]{{./Teratio-eeqs-Tm2-50000-Tw0-1000}.png}
    \label{eqecc}
    \caption{ }
  \end{figure*}
#+END_SRC

#+BEGIN_SRC latex
  \begin{figure}[htb]
    \centering
    \includegraphics[width=0.3\textwidth]{{./Teratio-pomega-Tm2-50000-Tw0-1000}.png}
    \label{eqecc}
    \caption{ }
  \end{figure}
#+END_SRC

###

In this treatment, we also compare the effects of secular
terms by turning them off for identical initial conditions.  As it
turns out, for $q$ near unity, the secular terms are largely
unimportant for the equilibrium state.  At more extreme mass ratios,
i.e. $\abs{\log q}\approx 2-3$, equilibrium eccentricities are larger
and so secular contributions can alter the equilibrium state.

###

This behavior can be understood from equation [[eqref:doteta]]. If we
adopt the fiducial value $T_{m,1}=\infty$ and assume
$\dot{\eta}\approx 0$, we can solve for $\epsilon=e_1/e_2$ as

\[\epsilon^2(\beta) \approx \frac{\beta}{\delta-1}\left(
\frac12\frac{(T_{e,2}/T_{m,2})}{e_2^2} +\frac\delta\gamma -1\right),\]

where $\beta=T_{e,1}/T_{e,2}$, $\gamma=q\sqrt{\alpha_0}$, and
$\delta = j(q/\alpha_0+1)$.

###

After a canonical rotation $\theta\to\theta+180^\circ$, the phase
spaces are identical; this corresponds to flipping the sign of the
third term in the equation eqref:hhat.  Hence, we'll focus on the
solution along the line $\theta=0^\circ$.

###

###

###

###

** Large initial eccentricities
*** figures                                                        :ignore:
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{e0large-h-0.10-Tw0-10000-cut-0.30}.png}
  \caption{Here we again have an example with $h=0.1$, $q=2$, but set
    the initial eccentricities to $e_{i,0}=0.3$ and
    $T_{e,0}=10$~kyr. The system misses the circular resonances
    altogether and remains apsidally aligned throughout.}
    \label{fig:e0large}
  \end{figure*}
#+END_SRC
*** e init                                                         :ignore:
Another way of avoiding capture into the circular $\theta_i$
resonances altogether is to have a large initial eccentricity when the
periods $P_2/P_1$ reach the nominal resonance value of $1.5$.  In
Figure ref:fig:e0large , we demonstrate the feasibility of MMR
apsidal-alignment when the planets $m_1$ and $m_2$ are given large
initial eccentricities of $e_1=e_2=0.2$ by hand at the start of the
integration.

One weakness of this scenario is that the dissipative forces must be
shut off at some point after the system is captured into resonance but
before it evolves to a true equilibrium. If the disk forces were left
on for the entire simulation, the planets would reach the standard
equilibrium and "forget" their initial conditions.  Because of this,
we chose to set $T_{w,0}=10$ kyr rather than the standard 1 kyr. This
requires some fine tuning, but it is within the realm of possibility
as the protoplanetary disk does indeed dissipate over time. Depending
on other system parameters, the disk could indeed disappear before the
system reaches equilibrium, at which point the resonance would cease
to evolve.
* resonant eom
The resonant equation of motion for $R$ is
#+begin_src latex
  \begin{equation}
    \dot R_{\rm res} = -\frac{\d \hat H}{\d \hat\theta} = -2\sqrt{2R}\sin(\hat\theta) = 0
  \end{equation}
#+end_src
in resonance.  Hence, only dissipative and secular forces are at play
if $\hat\theta$ is operating.  The integrations in Figures
ref:fig:drivingex and ref:fig:e0large do not show qualitative
differences if the secular terms are turned off, and so the apsidal
alignment must be due to dissipation. If we assume the semimajor axis
ratio is constant and consider only the dissipative effects on $R$, we
arrive at the following relation for equilibrium in $R$:
#+begin_src latex
  \begin{equation}
    \label{eq:diseqR}
    \cos\Delta\varpi \sim \frac{e_1^2 T_{e,2} + e_2^2 T_{e,1}}{e_1e_2(T_{e,1}+T_{e,2})}.
  \end{equation}
#+end_src
For reasonable disk parameters ( $h\sim 0.1$, $T_{e,i}\sim h^2
T_{m,i}$ ), the right hand side of equation eqref:eq:diseqR
is order unity, and so we see that $\Delta\varpi\approx 0$.

* second fundamental model of resonance
#+BEGIN_SRC latex
  \begin{figure*}
    \centering
    \includegraphics[width=0.7\textwidth]{{./phasediag}.png}
    \caption{\emph{Left}: Equilibrium points for the Hamiltonian in
      equation (\ref{hhat}) for various values of $\delta$ are
      plotted in black.  The green lines indicate the $\delta$ values
      used for the right two phase diagrams, along with their
      associated equilibria.  The resonance zone for $\delta>0$ is
      shaded in red.  \emph{Middle}: Phase diagram for
      $\delta=-0.5$. There is only a single equilibrium and resonance
      zone to the right of the origin.  \emph{Right}: Phase diagram
      for $\delta= 1$. There are three equilibria; the separatrix
      passes through the leftmost equilibrium point, which is a
      saddle point in phase space. The small lobe of the separatrix
      encloses a circulation zone with a stable equilibrium near the
      origin. The leftmost equilibrium point is located within the
      resonance zone in between the two lobes of the separatrix.}
    \label{fig:phasediag}
  \end{figure*}
#+END_SRC
The Hamiltonian in [[eqref:hhat]] is known as ``the second fundamental
model of resonance''. Its phase space is well studied in the
literature, so we will only review it briefly, following the approach
in cite:henrard_second_1983.  The choice of polar coordinates in
equation [[eqref:hattheta]] introduces a virtual singularity at $R=0$
cite:henrard_second_1983.  If we switch to the canonical Cartesian
coordinates $\xi = \sqrt{R}\cos\theta$ and $\nu = \sqrt{R}\cos\theta$,
$\hat H$ becomes

#+begin_src latex
  \begin{equation}
    \hat H(\xi,\nu) = -3(\delta+1)(\xi^2+\nu^2) + (\xi^2+\nu^2)^2 -2\sqrt2
    \xi
  \end{equation}
#+end_src

In equilibrium, $\dot R = \d\hat H/\d\theta \propto \sin\theta= 0$,
and so we see that equilibria must lie along the line $\nu=0$ in phase
space.  The left panel of Figure ref:fig:phasediag displays the
results of solving the equation $\hat H(\xi, 0) = 0$ for $\xi$
numerically for various values of $\delta$.  For $\delta<0$, there is
one equilibrium point to the right of the origin; for $\delta \geq 0$,
a separatrix appears which divides the phase space into 3 regions:
outer circulation (outside the separatrix), inner circulation (within
the inner lobe of the separatrix), and the resonance zone (between the
inner and outer lobe of the separatrix).  The resonance zone is
indicated in red in the left panel of Figure ref:fig:phasediag.  The
right two panels of Figure ref:fig:phasediag display the phase space
for choices of positive and negative $\delta$.

* theta stuff

For the case $e_1=0$ and $\mu_2\ll\mu_1$, the system's conjugate
momentum takes the form $R\sim e_1^2$ with coordinate $\hat \theta =
\theta_1$, and vice versa for $e_2=0$, $\mu_1\ll\mu_2$.  These parameters
describe the standard scenario of a test particle near an MMR with a
massive planet on a circular orbit, the derivation of which may be
found in cite:murray_solar_2000. The parameter $\delta$ describes the
system's depth into resonance.


Since the canonical momenta of the circular angles $\theta_i$ have
$R_i\propto e_i^2$, resonance capture widths $\delta a_i$ are
functions of $e_i$ as well. Hence, for large eccentricities near the
resonance location, $m_1$ and $m_2$ may not be captured into
resonance. However, if we consider the Hamiltonian system $H_{\rm
Kep} + H_{\rm res}$ in eqref:hamiltonian as a whole, i.e. considering
$m_1$ and $m_2$ simultaneously, there is one resonance angle
$\hat\theta$ that describes the system's dynamics which may operate
separately from $\theta_1$ and $\theta_2$.

* coefficients
#+BEGIN_SRC latex
  \begin{align}
    \mathcal M
    &= \frac{1}{(1+q)^3}\left(
      \frac{jq^3}{\Lambda_1^3} - \frac{(j+1)}{\Lambda_2^3}
      \right)\\
    \mathcal N
    &= \frac{1}{(1+q)^3}\left(
      \frac{jq^3}{\Lambda_1^4} - \frac{(j+1)}{\Lambda_2^4}
      \right).\\
    \mathcal K
    &= \frac{1}{(1+q)^2\Lambda_2^2}\sqrt{\frac{\Lambda_1}{2}}\frac{1}{f_1\sqrt{f_1^2+\alpha^{1/2}f_2^2}}
  \end{align}
#+END_SRC


In ref:fig:phasediagsex, we display the phase spaces from all three
integrations plotted in the previous sections.
The top row displays the $(\theta_2, \propto e_2)$ conjugate pair.
The standard setup enters a tight resonance quickly and stays there (indicated by the small yellow region).
Driving $e_2$ to a value $e_{2,d}=0.3$ leads to an early libration, indicated by the blue-green inner lobe.
The planet $m_2$ then enters the outer circulation region and reaches equilibrium.
On the contrary, the simulation with both $e_1 = e_2 = 0.2$ starts well outside the separatrix (purple).
Dissipative forces push the system closer to the separatrix; then, the disk forces cease
and the system remains in the circulation region. This way, the system never enters the $\theta_2$
resonance. The $\theta_1$ resonance is similar.

On the other hand, the bottom row of ref:fig:phasediagsex displays the
phase space for $(\hat\theta,\propto \hat e)$.
All three systems end up in resonance. The standard picture is a very tight resonance, while the
$e_2$ -driving and large $e_0$ systems enter stable libration in the resonance zone.
The two apsidally aligned cases therefore end up in analagous phase space configurations, but
through different dynamical paths.

*** Second fundamnetal model of resonance
Now, all that is left to do is to rescale equation eqref:eq:HShat
into what is referred to as
the "second fundamental model of resonance" citep:henrard_second_1983.



@@latex:\note{
Now transform into $\hat R$
}@@


** Elliptic restricted 3 body problem

@@latex:\twocolumn@@
bibliography:references.bib
bibliographystyle:mnras

and relegate the internal case
to Appendix [[*Elliptic restricted 3 body problem][Elliptic restricted 3 body problem]]. 
